### PR TITLE
Trying to fix #1916

### LINKED ISSUE #1916: Select box options not matching state on select change event
I have a select box with options 0 to 5. Select box onchange event will always set the selected state to 5. On first selection of any option, it does select 5,  however not in subsequent selections.

## Expected Behavior
On any subsequent selections, the option should remain as 5.

## Current Behavior
However, subsequent selections, does not remain 5.

## Possible Solution
Hoping i'm not the one to fix it.

## Steps to Reproduce (for bugs)
https://jsfiddle.net/7tj9pyet/ with Mithril 1.1.3, tested on Chromium and Vivaldi.

### PR DESCRIPTION
**Pull request by robinchew**
Select change event does not update options correctly. This fix will correct it but test fails.

Issue #1916

### CODE REVIEW

**Comment by botvac** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please add an entry to <a href="https://github.com/robinchew/mithril.js/blob/issue1916/docs/change-log.md">docs/change-log.md</a>.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by isiahmeadows** [comment]
Your error is [running into this problem](https://github.com/MithrilJS/mithril.js/blob/next/test-utils/domMock.js#L6), but it's not your fault. @pygy Me thinks this is a good time to fix it? [It seems a bit simpler than what we currently have, ironically enough.](https://html.spec.whatwg.org/multipage/form-elements.html#dom-select-selectedindex)

**Comment by pygy** [comment]
@isiahmeadows I'll look into the DOM spec details this weekend. I don't think the mocks have a concept of dirtiness for `option`s, and currently setting the `value` of a `select` doesn't change the `selected` attributes of the children.

**Comment by isiahmeadows** [comment]
If I'm reading the spec correctly, I think the concept of dirtiness is really just a (IMHO poorly named) locking mechanism for the [`selected` *HTML attribute*](https://html.spec.whatwg.org/multipage/form-elements.html#concept-option-dirtiness) (as opposed to the [IDL-side `option.selected` getter/setter](https://html.spec.whatwg.org/multipage/form-elements.html#dom-option-selected)). If we opt to not support the attribute, I'm not sure we need to implement the "dirtiness" value.

**Comment by isiahmeadows** [comment]
@pygy Can we merge this PR first, adding a tracking issue for the broken `options.selected`, and then once one of us gets this magical thing called *time* (:smile:), come back to fix it?

**Comment by tivac** [comment]
If this gets merged w/ failing tests it's gonna need someone committing to fix the tests soon after. I think the PR is fine, but I'm really uncomfortable with leaving the build broken.

**Comment by isiahmeadows** [comment]
@pygy @tivac Are you okay with this?

BTW, I instructed @robinchew on Gitter to include the commented out test because I plan to migrate most of the tests to run on the DOM as well if it's available (better test coverage), and I'm more likely to remember to test for this particular bug if it's already there.

**Comment by pygy** [comment]
@isiahmeadows let's merge it with a stubbed test, yes (a failing test in `next` would be a pain to work around while working on other aspects of the code base).

**Comment by isiahmeadows** [comment]
@pygy So beyond that, does this PR look okay to merge?

**Comment by pygy** [comment]
@isiahmeadows I'd say yes

**Pull request merged**
