### PR TITLE
Update all repo references after the great migration

### PR DESCRIPTION
**Pull request by tivac**
Did a pass to convert all `lhorie/mithril.js` refs into `MithrilJS/mithril.js`. Also all `rewrite` branch references to `master`.

### CODE REVIEW

**Comment by tivac** [comment]
@pygy @isiahmeadows @lhorie could I get a buddy please? Should be pretty safe, but still a slightly scary change.

**Comment by isiahmeadows** [comment]
@tivac I plan to track down and update all the relevant community projects (e.g. mithril-node-render), which will be a little more ad-hoc.

**Comment by isiahmeadows** [comment]
If I beat you to it finishing, I'll see what I can do.

**Comment by lhorie** [comment]
lgtm

**Pull request merged**
