### PR TITLE
m.request: don't append interpolated data to query

### PR DESCRIPTION
**Pull request by barneycarroll**
As raised by @fuintis on [February 21, 2017 12:02 AM](https://gitter.im/lhorie/mithril.js?at=58ab83b07ceae5376a18113a):

> when i use m.request with a dynamic url and i assign an object to the "data" XHROptions attrib, the url is correctly interpolated, but the "data" object is appended like query string
> //url/:id -> //url/wrong?id=wrong
> tested only with GET method, and mithril 1.0.2
> is this an issue or there is an option to alter this behavior?

This patch ensures interpolated keys are deleted from the `data` object.

Bug case: https://jsbin.com/meqiyi/edit?js,output
Fix case: https://jsbin.com/gisiqu/edit?js,output

### CODE REVIEW

**Comment by pygy** [comment]
Modifying user-provided objects is suboptimal...

Maybe you could instead create another object with the attrs that weren't used used to parametrize the URL?

**Comment by barneycarroll** [comment]
@pygy yeah, that was my thought process while reading the code. The code didn't always mutate user-provided objects – [there was a patch for this](https://github.com/lhorie/mithril.js/commit/4a98bb050320ef02513c305e8a5b5e86e04645e7) ([and there's till a test for it, commented out](https://github.com/lhorie/mithril.js/blame/next/request/tests/test-request.js#L393-L404)). It looks like @lhorie had merge conflicts from several incoming request patches and went for the Alexandrian solution.

**Comment by barneycarroll** [comment]
[Oh cool](https://travis-ci.org/lhorie/mithril.js/builds/203765340#L214-L216)
```
[object Object]
should deep equal
[object Object]
```

**Comment by pygy** [comment]
IMO taking ownership (and therefore mutating) `vnode`s and `vnode.attrs` makes sense for perf reasons, but here I'd leave `data` and its fields alone.

**Comment by FibreFoX** [comment]
@pygy Is there any decision about how to handle this?

**Comment by pygy** [comment]
This ties into #1699 and the general design of the `m.request()` params. I'm not very familiar with the details of m.request, I'll have to think about the whole thing but no time right now.

**Comment by isiahmeadows** [comment]
Missed this, but superceded and resolved by #2361

**Comment by FibreFoX** [comment]
@isiahmeadows does this PR close this issue too? #1699

**Comment by isiahmeadows** [comment]
@FibreFoX Yep and done.

**Pull request closed without merging**
