### PR TITLE
Release - v2.2.6

### LINKED ISSUE #2842: Leftover DOM elements when switching between fragment and element
**Mithril.js version:** v2.0.4-156-gad9aa97d

**Browser and OS:** Firefox on Linux.

**Project:**

## Code

```javascript
var toggle = true;
m.mount(document.body, {
    view: function() {
        return m('div', { onclick: () => toggle = !toggle },
          toggle ? 'text' : [ 'fragment', 'b' ],
          m('br') // extra element is needed to trigger the issue
         )
    }
})
```

[Flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AbhgBOAAmK0A5vNjSAvLMkBXGAG4AOmiz4stDQwAUAE1rUNOBvgBGtCwE8K04PunfpYiDAB3RGkwU2piCHozAEoPLx8EyRhiDUk0aSwzAHILCDEs92BpemooCGoAa2CY1QA+WQUlGFVpAEI5RWV2eISEjqbpAH5pLMYAD2Is6WDkEbBJDHk7SfcshymAXQoe3u9Mtcks2IB6Y+kYCYXz2GXpCDhpNBgYCxeG9QhFGBliQmb7uBaHa9aI7Vj6VjRSggOAwWDhSJoBA8AAciAATABaAAMiGxbA4IEwODw+GocAENHojGYPDYWxAZTQFWRqCJXDwWAgv0k0AAAk8JtDUuQeCRiAAHOCIU6mCUVeRk2hYY5cnn8gDM+Gx2sxguI+AAjABWVXcwi8qBGCBofD8aHEFwS7gw6i8iWiVgbVhAA)

## Steps to Reproduce

1. Load above code
2. Click a few times on the `<div>`
3. Observe that the `'b'` element from the fragment remains in the DOM after switching back to the non-fragment version.

### PR DESCRIPTION
**Pull request by JAForbes**
# Release v2.2.6

<a name="changeSummary-start"></a>

- #2981
- #2979

<a name="changeSummary-end"></a>
        
## Changelog

<a name="changelog-start"></a>
#### [m.domFor(): workaround for unintentional mangling. Fix #2842 (@kfule)](https://github.com/MithrilJS/mithril.js/pull/2981)

Refactoring of domFor() for the internal bundler.  https://github.com/MithrilJS/mithril.js/blob/cfa890f68571df1ab8543097f7fa61c34ee93683/mithril.js#L157.
#### [Drop Istanbul to kill install warnings (@dead-claudia)](https://github.com/MithrilJS/mithril.js/pull/2979)

Title's pretty self-explanatory.  Also, this isn't really used much in practice.  From a local run: ```.  $ npm ci.
               
<a name="changelog-end"></a>

### CODE REVIEW

**Comment by JAForbes** [comment]
@MithrilJS/admins any objections to pushing thing out to fix #2842 ?

**Comment by dead-claudia** [comment]
@JAForbes There's my list of objections. 😉

**Comment by kfule** [comment]
@JAForbes @dead-claudia 
There seems to be an error in the release workflow and it is not being published to npm.
https://github.com/MithrilJS/mithril.js/actions/runs/11135318559/job/30945104134

**Comment by JAForbes** [comment]
@dead-claudia I think you'll need to take a look

**Comment by dead-claudia** [comment]
Sorry, looking at it now. Trying a re-run to see if it resolves itself: https://github.com/MithrilJS/mithril.js/actions/runs/11189351374

**Comment by dead-claudia** [comment]
Take ~~2~~3, using the right branch this time: https://github.com/MithrilJS/mithril.js/actions/runs/11189421869

**Comment by dead-claudia** [comment]
Okay, v2.2.8 published. v2.2.6 and v2.2.7 got skipped due to the prior deployment failures. Turns out I needed to add a `--force` to the `git push` in that script, but that was it.

**Pull request merged**
