### PR TITLE
Resources / Learning section

### PR DESCRIPTION
**Pull request by cavemansspa**
@CreaturesInUnitards suggestion per #1809

### CODE REVIEW

**Comment by isiahmeadows** [comment]
@pygy I requested the review [due to this comment](https://github.com/lhorie/mithril.js/issues/1809#issuecomment-296662489).

**Comment by CreaturesInUnitards** [comment]
IMHO if you're going to include my screencasts — which is very flattering, and thank you — it might be better to just link to the playlist, rather than to the individual parts. There are at least 10 more to come!

**Comment by CreaturesInUnitards** [comment]
@cavemansspa I'd suggest changing your PR to this one link: https://scrimba.com/playlist/playlist-34

**Comment by cavemansspa** [comment]
@CreaturesInUnitards sounds good.  let's see where @pygy and co. decide on the learning materials location and i'll adjust accordingly.

just wanted to nudge this one along so that your efforts on putting together the scrimbas can be accessed from the main mithril site.

**Comment by CreaturesInUnitards** [comment]
@cavemansspa thanks so much! I really appreciate it. TBH I thought about doing this PR myself, but it's WAY better that someone else do it 😃

**Comment by cavemansspa** [comment]
@pygy @tivac any further thoughts on adding a "Learning" section to the docs?

**Comment by isiahmeadows** [comment]
@cavemansspa I'm good with this as a start, but having more resources later would be *really* nice. 😄

**Comment by isiahmeadows** [comment]
@cavemansspa Let's just do a single link to his screencasts at the beginning of the "Getting Started" section of the homepage.

**Comment by CreaturesInUnitards** [comment]
FWIW the Scrimba folks are in the middle of updating their authoring tools; I have a bunch more content waiting for that update.

**Comment by cavemansspa** [comment]
@isiahmeadows -- just wanted to bounce back an "are you sure" you want to put under "Getting Started"? after having a look at reverting this pr and looking at adding to "Getting Started", i'm thinking maybe the separate "Learning" section might be easier for newcomers to see.

i believe others (@JAForbes) were considering adding some mithril learning content so expecting it's a section that will grow.

happy to proceed either way but just wanted to double check.

**Comment by JAForbes** [comment]
echoing @cavemansspa I think a Learning section is a good idea but for different reasons.  

I think "Getting Started" should be completely encapsulated.  Linking to other content (particularly at the beginning) creates the impression that those links are required in order to follow the getting started, whereas I think the current content is probably self contained as it is.

I want to avoid [Analysis Paralysis](https://en.wikipedia.org/wiki/Analysis_paralysis) / [Paradox of Choice](https://en.wikipedia.org/wiki/The_Paradox_of_Choice)

I think the exception is environment stuff, like setting up npm.  But for usage, I think it'd be helpful to keep "Getting Started" as self contained as possible.  A link (or links) at the end of "Getting Started" on the other hand isn't as overwhelming because by that point they've probably completely the tutorial and feel quite confident to tackle more content.

> i believe others (@JAForbes) were considering adding some mithril learning content so expecting it's a section that will grow.

I don't have any plans to do any "How to Mithril" sort of videos, but I am working on a streams series (that features mithril) and but that should definitely be tackled after resources like @CreaturesInUnitards series, and certainly after the "Getting Started".  So I can see a Learning section being valuable for that.
Whenever I've updated my mithril blog posts ( e.g. [How I use Mithril](https://james-forbes.com/?/posts/how-i-use-mithril) ), it'd be a good place to link to them too (if no-one would be opposed).

So I'm 👍 for a separate Learning section.

**Comment by isiahmeadows** [comment]
If there's an expectation for the "Learning" section to grow, then let's go ahead and have a dedicated one. (My request was under the assumption it wouldn't likely grow anytime soon, but if I'm wrong, then having a new section makes more sense.)

**Comment by isiahmeadows** [comment]
@pygy Ping?

**Comment by tivac** [comment]
Looks good to me, we can always reshuffle later if things change.

**Pull request merged**
