### PR TITLE
Fix wrong link targets and typos

### PR DESCRIPTION
**Pull request by StephanHoyer**

### CODE REVIEW

**Comment by StephanHoyer** [comment]
BTW I think `m.stream()['fantasy-land/of']` can be dropped. It's not required by fl-applicative spec, as I see. If you want, I can make a PR for this.

**Comment by tivac** [comment]
I've got zero expertise or insight into the fantasy-land stuff. If you have a recommendation I'm all ears.

**Comment by isiahmeadows** [comment]
@tivac @StephanHoyer Fantasy Land switched to `ap.constructor["fantasy-land/of"]()` instead, for pragmatic reasons. That's the long and short of it.

**Comment by StephanHoyer** [comment]
@isiahmeadows yes I saw this. Maybe we should change this. Will create a PR tomorrow

**Pull request merged**
