### PR TITLE
Tell unpkg to send the right bundle

### PR DESCRIPTION
**Pull request by isiahmeadows**
## Description

See https://github.com/unpkg/unpkg.com/issues/63#issuecomment-326722967

## Motivation and Context

Apparently unpkg has been [looking to make some significant changes](https://github.com/unpkg/unpkg.com/issues/63), and this is what they're deprecating `browser` handling in favor of. Also, `unpkg` is unhelpfully redirecting `https://unpkg.com/mithril` to `https://unpkg.com/mithril@1.1.6/index.js` and we should probably fix this soon.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have updated `docs/change-log.md`

### CODE REVIEW

**Comment by barneycarroll** [comment]
Ironically, the canonical issue on their side describes a problem of the modulo `unpkg` field of `package.json` not being respected. As it turns out, the underlying bug is that package manifests aren't being read at all anymore. Unless I'm mistaken the correct course of action from Mithril's side is to patiently wait for them to revert the breakage.

**Comment by isiahmeadows** [comment]
Yeah, let's delay this until we know what's going on on their end, and then we can revisit this.

**Comment by isiahmeadows** [comment]
BTW, this will let us drop our existing `"main": "mithril.js"` and let it default to `index.js`, making interop between the various entry points a little easier.

**Comment by isiahmeadows** [comment]
And for reference, I found the unpkg bug we're blocked on: https://github.com/unpkg/unpkg.com/issues/156

**Comment by pygy** [comment]
The unpkg bug is fixed.

**Comment by isiahmeadows** [comment]
@pygy So WDYT about this?

**Comment by isiahmeadows** [comment]
I retagged it because it's not really a bug at this point.

**Comment by isiahmeadows** [comment]
BTW, this will only need merged if we choose to make `index.js` the main entry point rather than `mithril.js`.

**Pull request closed without merging**
