### PR TITLE
【Fix #1998】change to share routes instance in xhrMock.

### LINKED ISSUE #1998: mithril request API is difficult to test
mithril request API is difficult to test

I attempted to do unit tests using mithril and ospec, but in the following case we could not test with require cache.
everyone, How do you solved this problem?

A.js
```javascript
const m = require('mithril');

module.exports = class A {
  constructor() {
    this.hoge = [];
  }

  get() {
    return m.request({
      method: 'GET',
      url: '/api/v1/users/:id',
      data: { id: 1, name: 'test' },
    }).then((result) => {
      this.hoge.push(result);
    });
  }
};

```

B.js
```javascript
const m = require('mithril');

module.exports = class B {
...
```

ATest.js
```javascript
const o = require('mithril/ospec/ospec');
const browserMock = require('mithril/test-utils/browserMock.js');

o.spec('A', () => {
  let a;

  o.beforeEach(() => {
    global.window = browserMock();
    global.document = global.window.document;

    const A = require('../A');
    a = new A();
  });

  o('Acquire server', (done) => {
    global.window.$defineRoutes({
      'GET /api/v1/users/1': () => {
        return {
          status: 200,
          responseText: JSON.stringify({ type: 'Foo', id: 1192 }),
        };
      },
    });

    a.get().then(() => {
      o(a.hoge[0].type).equals('Foo');
      done();
    });
  });
});
```

BTest.js
```javascript
const o = require('mithril/ospec/ospec');
const browserMock = require('mithril/test-utils/browserMock.js');

o.spec('B', () => {
  let b;

  o.beforeEach(() => {
    global.window = browserMock();
    global.document = global.window.document;

    const B = require('../B');
    b = new B();
  });

  o('Acquire server', (done) => {
    global.window.$defineRoutes({
      'GET /api/v2/users/1': () => {
        return {
          status: 200,
          responseText: JSON.stringify({ type: 'Foo', id: 1192 }),
        };
      },
    });

    b.get().then(() => {
      o(b.hoge[0].type).equals('Foo');
      done();
    });
  });
});
```

## Expected Behavior

All green

## Current Behavior

```shell
$ npm run test

> hoge@1.0.0 test /Volumes/Transcend/dev/hoge
> ospec

Possible unhandled promise rejection: Error: server error, most likely the URL was not defined /api/v2/users/1
    at Object.deserialize (/Volumes/Transcend/dev/hoge/node_modules/mithril/mithril.js:358:20)
    at XMLHttpRequest.xhr.onreadystatechange (/Volumes/Transcend/dev/hoge/node_modules/mithril/mithril.js:293:82)
    at Immediate._onImmediate (/Volumes/Transcend/dev/hoge/node_modules/mithril/test-utils/xhrMock.js:58:63)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
B > Acquire server:
async test timed out

    at ontimeout (timers.js:488:11)

3 assertions completed in 229ms, of which 1 failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hoge@1.0.0 test: `ospec`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hoge@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ytetsuro/.npm/_logs/2017-10-19T19_11_29_200Z-debug.log
```

## Possible Solution

delete mithril from require cache.
Also, I do not think that deleting require cache is a good code.

## Context

mithril request API is difficult to test

## Your Environment

* Version used: 1.1.5
* Browser Name and version: None
* Operating System and version (desktop or mobile): mac OS 10.12.6

### PR DESCRIPTION
**Pull request by ytetsuro**
## Description

Since xhrMock does not share routes, it does not change permanently from the routes variable of window bound at mithril require.
As a solution approach, I changed the routes variable rewritten with xhrMock like singleton.

## Motivation and Context

#1998

## How Has This Been Tested?

I tested this pull request in the following.

* Run code written on the issue.
* Run tests by adding tests that fail with existing code.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I have updated `docs/change-log.md`

## Question

👇 I will leave this comment for discussion, the answer is [this](https://github.com/MithrilJS/mithril.js/pull/2233#issuecomment-426844267).

I am PR to `next` as in `CONTRIBUTING ` had been written, but this will also be reproduced in the `master` branch.
Should I submit PR to the `master` branch?

### CODE REVIEW

**Comment by pygy** [comment]
Thanks for the PR @ytetsuro but I'm not sure this is the right way to solve this issue... It is technically breaking, since it prevents one from defining several mocks that can be used concurrently...

It could be better to expose the `$defineRoutes()` method of the mocks... Maybe as m.request.$defineRoutes?

It isn't a problem we'd face in the Mithril code base though, nor in any sensible test suite built on top of ospec (where the tests are run in series, even the async ones).

**Comment by isiahmeadows** [comment]
@pygy I've advocated in the past for making our mocks an internal thing, not exposing it to users.

@ytetsuro 

> Should I submit PR to the `master` branch?

No. We develop on `next`, and it gets eventually mirrored onto `master` (either docs build or release IIRC).

**Comment by ytetsuro** [comment]
@pygy 

Thank you reply.
I'd like a sample to see what kind of case it will break.
Should I close this PR and discuss better ways with the issue?

@isiahmeadows 

Thank you reply.
I understand.

**Comment by pygy** [comment]
@ytetsuro the breaking change is quite theoretical, I doubt anyone uses the mocks like this:

```
var a = browserMock()

var b = browserMock()

a.$defineRoutes({...someRoutes})

b.$defineRoutes({...otherRoutes})
// now the `a` routes have been overwritten by the ones defined on `b`.
```

But see my comment in #1998, you may not need a patch after all.

**Comment by ytetsuro** [comment]
@pygy 

I read the comment of #1998.
The code I wrote in your comment was very perfect.
I do not need this change.

I'm really thankful to you.

**Pull request closed without merging**
