### PR TITLE
Mocks: Add event propagation (and pave the way for more event options)

### PR DESCRIPTION
**Pull request by pygy**
As discussed in Gitter this implements adding capture phase events via hyperscript.

I've also added event propagation, eventPhase and currentTarget support in the mocks (with tests).

@tivac seems to be against the first change, so I'm waiting for more feedback before I add framework tests (if at all).

## Description

```JS
m.render(root, m('div', 
  {
    // calling e.stopPropagation here would stop further handlers from firing
    onclick_capture(e) {console.log(1)}, 
    onclick() {console.log(3)}
  },
  m('button', {onclick(){ console.log(2) }, "clicky"})
))
// click the button, logs: 1  2  3
```
 This can be useful in event delegation scenarios where `e.target` points to the event that triggered the event while `e.currentTarget` points to the element on which the event was defined.

## Motivation and Context
@spacejack wondered if we could support it. React has a similar scheme (`onClickCapture`).

## How Has This Been Tested?

Not yet (it doesn't break the current tests).
Edit: `node.removeElementListener()` also needs some tests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I have updated `docs/change-log.md`

---

Edit: Actually I can already see a bug from here: if an element has both a capture and bubbling-phase handler and it is the target, its events will fire twice :-/

Edit2 : the way I implemented `stopPropagation()` actually corresponds to [`stopImmediatePropagation()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation)... :-/ again!

### CODE REVIEW

**Comment by spacejack** [comment]
Some related [React discussion](https://github.com/facebook/react/issues/6436). What do you think about [this suggestion](https://github.com/facebook/react/issues/6436#issuecomment-254331351)?

**Comment by pygy** [comment]
@spacejack that's interesting... I'll fix the `stopPropagation()` issue, remove the `_capture` thing and open a distinct issue for mooting over the various `addEventListeners` options.

**Comment by pygy** [comment]
Oh, joy and timing... It turns out that, for the events on target, the handlers are called in their definition order, regardless of the phase they were ascribed to. So

```
div.addEventListener("click", cap, true)
div.addEventListener("click", bub, false)
div.onclick = legacy
```

will fire `cap`, `bub`, `legacy`, and 

```
div.onclick = legacy
div.addEventListener("click", bub, false)
div.addEventListener("click", cap, true)
```

fires `legacy`, `bub`, `cap` when that div is clicked.

If a parent is clicked, the legacy handler is part of the bubbling phase.

Also, 

```
div.addEventListener("click", cap, true)
div.onclick = legacy
div.addEventListener("click", bub, false)
div.onclick = legacy
```

fires `cap`, `legacy`, `bub`, but 

```
div.addEventListener("click", cap, true)
div.onclick = legacy
div.addEventListener("click", bub, false)
div.onclick = null
div.onclick = legacy
```

fires `cap`, `bub`, `legacy`, so we'd have to define getters/setters for every legacy event handlers, or be inaccurate. Provided that we don't use legacy event handlers in core I'd rather avoid the overhead of 48 getters per mock DOM node.

**Comment by isiahmeadows** [comment]
@pygy Feel free to omit the numerous legacy getters, since core should *not* be using them. If there's any tests using them, they need fixed, too.

As for the overhead, it wouldn't be as much of an issue if we'd actually fix the mock to use prototypes instead of closures. Might speed up the tests some, too.

**Comment by pygy** [comment]
@isiahmeadows That could be a good idea (re. prototypes). We'd have to use a property as a stash for the private state though. This PR will expose the (officially private) event handlers list as `_events`.

**Comment by isiahmeadows** [comment]
Regarding the whole concept of adding capture support, I'm kind of 0 on it. I've been investigating other ways for separate reasons (writing my own DOM framework - too much of a JS programmer 😄), and I've come up with this alternative:

```js
// Simple non-capturing
onclick: e => ...,

// Capturing, passive, etc.
onclick: [{capture: true, passive: true}, e => ...]

// Multiple listeners
onclick: [
    e => ...,
    [{capture: true, passive: true}, e => ...],
]
```

Not too sure about performancewise, but it definitely dodges the naming oddity, and it's helpfully a lot more extensible. (`passive` listeners are helpful for avoiding jank, and a I've read from lot of people saying it should've been the default.)

**Comment by pygy** [comment]
That seems better, actually (or a variation thereof). I'll make the mocks amenable to extra options (even if `addEventListener()` doesn't support it right now).

**Comment by isiahmeadows** [comment]
@pygy It's not perfect, but IMHO it's better than pretty much everything else I've come up with so far. (FWIW, I've spent the last few months or so just on the design of this framework I'm working on, and have only just started coding any of it.)

**Comment by isiahmeadows** [comment]
@pygy Although this might work a little more fluidly and aesthetically (just came up with it now):

```js
// Normal
onclick: e => ...

// With opts
onclick: ["passive", "capture", e => ...]

// Multiple
onclick: [
    e => ...,
    ["passive", "capture", e => ...],
]
```

**Comment by thysultan** [comment]
I think an object that assume a similar shape to the `EventListener` interface would work well with the push to support the `EventListener` interface.

```js
interface EventListener {
    handleEvent: function
    handleCapture: boolean|object
}

m(.., {
    onclick: {
        handleEvent: () => {},
        handleCapture: true,
    }
})
```

**Comment by spacejack** [comment]
How about this:

	// Callback
	onclick: function

	// EventListener object
	onclick: {handleEvent: function}

	// Custom Mithril object
	onclick: {
		handler: function | EventListener,
		capture?: boolean,
		passive?: boolean,
		once?: boolean,
		//futureProp...
	}

	// Array of any of the above objects for multiple listeners. Eg:
	onclick: [
		e => {},
		{handleEvent: e => {}},
		{handler: e => {}, capture: false, passive: true, once: true}
	]

IMO the various types should be disambiguated. Mithril's options object could be the same shape as EventListenerOptions with the additional handler property: `EventListenerOptions & {handler: function}`

    if (typeof o === 'function') // callback
    if (o.handleEvent) // event listener object
    if (o.handler) // Mithril's custom object with options properties
    if (Array.isArray(o)) // Array of above

I kind of think it should go all the way (with the exception of the array - maybe that's overkill?) and future proof for additional options, or not at all (and have people resort to adding to the DOM directly.) `passive` looks to be the most important option to support, but unlike React it would trigger full redraws in Mithril so might not be used as much.

**Comment by tivac** [comment]
I don't think an array of handlers should be supported in core, that's trivial to add in userland if you want it.

Otherwise I'm fine with the three options @spacejack proposed, but I still question the necessity.

**Comment by pygy** [comment]
So I've updated this to be mocks-only, and to only support a boolean `useCapture` parameters rather than the full options. Here [are the tests running on the real DOM](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AbhgBOAAgAmEMRWkwlcAA4BPJQBJZtagFccDaQF5pwVgB00tfACMYYWpJgBRDNUIAKMAbTUxBD03gCUFjbS0uoaZtJ2MWGRcgpxeobGxPjUrhiMbrCZ3lYg8mIlockwafpGItm5+WIixSAAsrQGcO7NDHAVVfgQaBDEbr3ErdRQENQA1iVKxJIGKtLLq5VoUbq1mQ60srHm6XUMDTB57oUtJfaHGgPb0rsZ9fdH+BhqakyyAMKEaCybxlLasLZ2DBgRiSDxeXz+QLBNBhCLPV5nLIfDT4VxYWjNQHA0EKcFbGy0Vr4wk9EQAGQgcEYaBgMgA7i45nBpN57AZ7PYZmgAObSNSEDDdSqUaR+AJBELhYDJMpfWSycYMpkstlTGbzRbRTRKMAYKDS1UKPEwAnNLUMRnMph6krTWYLWUxU3my3PNXydR5LwOyYwCnPKkxbLmqD-ToMUL4GAARwMvu8AAZyZTqbbaaGnbqOVyed5qN9iAZXOLJZbZfLkUr0VE1RgNYWdS7JPqPUbvesVuGrWIbXa6Y6u6ye26DZ7VCbB5sR-hA2pg4RQ95h2hklHNDGoHGE8Qk6n0xasznbHnx53ndPpEzojBYMjmrz+YLhWKJVLhw2SKKqiyrJBIMi0MQhBsnECSaEk-rWu2moTEW3a9oaXqLmaFo7q2SEdqhU6ujQc5GpB0GSD6uFbPho40vaREPiR7qYQuWhyr6eEpKOa4bluO57t40YVke8b+KeyZphm2ZCRRbKHseElntJl4AIzXlSJQMROxBoY+z7dG+QQfuWlbVtUf71qaQEomiKrPOB8RQTB5hwRoCF0eqKHasxM6kX2WEcRs3FtoRvnFhh87OZRSxDrRPFjgWTGRbOgXsXFy6IbxTLrsQIYTNuEZRPuuKiUpiZSRecBXnJLmSIp4mVeeGYaTYEK5tp+aMRF3bxGgUCxDpPIudIkpoLIsAyK4UBXLI6y0NIGDSCKChMLW-68mpAD0ABMMo2Qqdmgdl3n3qlAVscawXxSuyHnehaVXQOOF+l5OkPdOUX9ouIUJQGuX8YVgmRsJB7lU1kktepmm3slvWPvQg3SMN6zQWNGATVNKOvnNC1LSta3bFZ1TeLte0HXKtnNg5Xn3Slj2XdFA5-Xd4WTn531BdRb2JR9DNfU9zPYVx-3Wnx+WbsDxXxGDZWxpDKnVd4bVoB1u43m65k1pj81fkKwxijAEw8vcUFyhANb0Gj1TEFIIowMQT7bKNLiyDBLmxOybLVO7kCsrISiuCKUiTfAPK0GANsbd0RqNsBvInVETndGmTDUNU5jIAAumBUjSBWahVjWbn4Ik8d2cboS01EL5pwEMD4GoXQ+FrRcWU8yQlduYhKxm3Hd8byYTAACnW4ZVRm+1d7LQ925IDtQ6pNVgjPVJD4YkiuAwAAq9uO33l6r886vJ-n+uwLBZfwRXIRVzXUSp6sDdNy3rQXzAnfPIPveT5eA+z1HMbEQY9-yHxqtPb+gD8Dz0XuA0kvc1492yNWbexA94LwPn-FeZJkjqzZj5DmF1WLRQ-jzUKBFCF6WIv5EhRpC7FzWKzU6EsCotBBt3BhFlGonngarbuH8eHKWwSrBKUZzzpwnu7GAag3DL28MgO4AohSf1lG3RhJRs6w3URZJaE1pAX0NsoE2BiKIWyti7dG640Fx2ptseyecZBP0kXEHOjiC7a0zvEa+Hlb6onvjPZxL9m5wFbjQTxX9a6APgQA9eQDR7jz4QlH+MD95L2VsfKJcSUFbxEBguBIjMT7BxAlU+0gnIfyvuXOxPdq6BIkcEt+SjvyqJlj-GJyToHAIYKA6UIiADMnTsmwKwdDHBiCoHZM3mg-Joz5FFPeA8UpMsFnnBxGdAWLEyKyjIZxGiyRVnYgeBshGWz0oePbq4TKFCcpBklgJGWVIuGuCEc1eR-DZaCIhrwkRHzxH1wzkmaRsj5GKPCZc1RShmkqM0dokAXQYD-E8XIJwGADBQGICNRar1IVUyOtbBxjl85BIzq43ORKZDWJEFUm+NSAlQJJY3EJYSqUMEibXOJHSkFD26cQXpE8xneEGdy0cIz0kZkyRy5B0y8lpPgYcg4RxlnuLFTS3xdLe4Pzrs-DOr9QmtDFey9pIjYnIN5fy+BkCsnILFfAyVKSZW7zlSIyV+CMSnGKcc+mpzaHbKUKy08BDPpnKuralcrCpbsMed4ANrzxUwyEmKuNSShKMqBTAGRcjlZgsNWokAAbYXtUhK0WAIdqCxHGmHSQPJIAWOjoY0UMdcV+MTi2cpxKGmkqzuSs+lKpDUtLtU-F-jNX1IBUypp+b+1spAG06JJqhlmoSWAgZi657OsFfa6Bjr0EbvmR6xZSq8EJScqqwdtLh21K1YyvVYTc1zs5QukVw8QGJJEVaqV67MHxvGWu0cO7Zk-oQcqjWOwD1rK9ezahnMhZGgDQlBV6z6AkLiAW063qiGMzobKMNLDAb3OljYISsbvnCMFR+qkSbSNvOVn84SnapEZpBdmkouaoVTpsXmgtIAtFFs6iAXlPI9DSFsE7NQkhaDrhDowfGXhgQicOPAWxl6k7tpkGe7xQ6mwjrqZM2pT69M8uXX08jf7UnfvleBo5R7DP-tQbKizhSrOKo0CB3tBcgRQHmue9VKma5urA3sQ9uIMPQeIX69Ycqg2bN9ecuTXmEPOfWRGh5RHQZUYVj8wVdH4uyGTSI2Sati0lEbsySTI8JNSbyCiaQO0ABsyntOtprk5QuI9p1Ox84iS94ZgCleIOVyrGBpPHTKa174gG1WeTUwYgUk2usnvzqWzwGh5uafgotmQX52toKm5t6Qy3y07YHetjyKykuQaofpEN0U2sdeuYloLEHPiheu7Fq6237t7N5oh45yG5xxEOxoY7bLQOJVezQrmShC6AYe9Fn1UPZv2Fh99m5+B-sekBzAMtq20lpa8ilwjYOnnfBB1kajQGcsTbSflwVhWBFzZpxT+B9PZZA8A7T+RrOqSfbQZz5W3PvBA7J-zmScL+uDck8N6r1tyYNcAsO5r7i7u7YW8r6n36pt+KKn1suA21AValyNpUY3z6M812rilB3scrbW+5abFSBRk72+44XHWXdg9+y9qDb3Ecq5EHD91T3rMhZ95D2DOyndfZxY9t4z3cQY-mFjnHZP8fg7DzBpm9CNeL0D3TDP4XzlfhRzHlcie5jJ9t3jsHAM7lsIYEVNPJODcddFwm0GMOmeZbI+8sRfJzeLzbzVOj7Ou9iSy73oSvP6jM4K33t3fPZ90+vPxiXBuhvG+2P07a8vDpNcJe5-3JhLeH5z47D37ni9pK13S6ua-DdVeAmEU3MhR8W9Ow7s39hncn5mwvk79u52weLmJymGgsWesoR+xAeeLwF23uV24eEBSg0+DA5CseWIIB5eleR2HWaeYUCBme2G0OZ+0BS4aOEOhBEWV+36aBZeAQAO5gb+i8eB4s+G9eYY0aUBQ+oiQkne363BdG1Bg+S+k+oMTBjsAhfeKB5O3eNGYuQk-+5wIhAu4ueukuj+NWAALDvo1gnAfjNlARfgYSQUYY7sjtfr-k5OIZ1h-trr1vfhvjLiBC-kjj-h-vtooTYYAWnl7qHgQYXldFATAb4aAWFlhlQVHmgrQUHnHiHujvQZjowTbjgTYjXpQsGu9rdiQTAfgRkYjkIY7NEV5FgUkTjoBiwbcnlOwY3sTmZC3ovrIZTn3nwcIY0SmqDAUTIePj3rRvPskbjvwcoa1FIZETPm0XPgof0SLkMZeIVurFpAJmoevkbk4dIAAKw6EK776qbjb1EAE+Kf4yAtHn6WFf524HEeH9HnGJD7bSE349Z35LEP7S5P6hAuGeEe4HJwF+F5ER7EF7GoFkHoGerwG-FIGuHR6ixfHAFIYJFJ6lErap5pGjgUEBFZFqAo7ML57+HhFF4D6FGo5iyjglHW5lHV7hpsGRoN4cKyxcEzHD7NEkGSFT74ldEVRNGTFkmDHjHZYjHf6t70k8FiFTECk8miHzGtAOErEJx1abF756E7H5yGGnFHEmEqmklV7v7eFW6dGmFf5uHanuYfFdZ2GPFlbLEaEm5AGxEgGom4mBGk5fZYmwEwmXZglEEQlRGEnQk2mwkoYIkpEiAVGhG+5-EXKYm3ToYF72mkKslFGJQknWHBmE5RpN51HTFim9G8FMmCmCGsnMnClcmtHdFyHt4M78kNElkcmFmImilVntESklZLEACSWAOA8gVwzxm+tWcpeK2xbauxBpBxppuu5prZ7ZEAnZjhrxLhxxXhFx7iup6p1hepW2oxx+7hruIpqum5nu3xIZiBHpQRQJPpGB6ydp4BHp0h8ZIRiZ25QZyJB5lBcW2RJ5UZOJl5ER5hNB3pp0d5RZjsyZlJqWtRdJmZwx2ZGJY+7JLOfJHOgpgu1h3Bgu0hyFfRKedZMFExRWq+LZbZMAHZjAXZqxcuuhNW+hg57u6pc59x2mOua+45BFk5RF05o2txrJq5Gp5a1xG2i56585NxW5GFO52pp5IJPxMWfujpXpzpIRF5N2Ro15v5gWvpf2cJFeAZwOuBj58lmR2eUFP5zpuRklYZnR8Zao-5mpzBj5KZ1JnB0lYx9ZvyjJBlxZWFvJLJ35blis2F3cSFCFfJGZTly+nJtZlZ7lXOK+msixY5+FhFMAxFCc2+u+fZCpA5SpDlG5hpxhrlJxu5l+HFJpt+o5+ujF8ViVbFQlVleV2VZhQ5glVuxpu5YlwWT5aJ+lZOwR+5ul+R-FN5+5llgZoO8OYBClkBr5Rl6RJl4JZlylCZ6l2BAx1lFJdeVJHBaZYFwVohnCOZ4FZZny+ZuZ6F1VbJPlIVHR-FaFoVQ1p1E+KhfG0VDFcVzFCVrF1s2hKVLaFFGVAJAlvFVuNF6pS5+Vf+VxFhthxVT1E5U50plVOp-FnFTVolMRZ5bp01R5mVpBsl3V0Zn5eJFZAec1t5C1mlSJI1YReNDpuVWNkZ2J7pX5JeUJf5JNXFS1gFNlwFROkFQVEVWZHeu1W1fN5Z8Fe1DJ11bNt1PREFF1BNShottUNZN1V1OFj1eF0NLFsN1sGxn1diSuANmNnFgNINZhPFZ2VV3F4NtV+pVFENDxJVkmZVL1FVVp5tWlIlC5e5rpoJ6NEWx52NXtElCOplfVRNA1LNnhwZPVYZc5ORU1QdM1cZc1Fl4dYN36QFq1IF3NmFZ121tJAtvN0twt0FOdQtbOqd3ld1hdB1stktpZYtitbtjlBdsxqhsV6tr1mt2wspOtiu31qpv1htapxtS25dNVHtBVXlY9DVE99V-1Rp95WVw5kNatTFMNlpzh1pqN3t8dGNv1XVAdbVMZilIdpeKN4l8R-prNZN759NL51NsdKJuNY1yBidp9xRKdAFxA6dVRa1NRWd4VJdVdzeItgtQD-ek9td1Zflo9kD7R5ZPNgD+1VInhBZjZAmW8LgI0hAEm7I2wwwGMWMbIQm9AAA5E7MMLCCsEXNHF4BgMMGRSEHoKyIqTIGyJIG0HAGKOYCUDvFYq4N0A3PEFHC5N0NEBAAAB7KAYPVrOzRxQC0BijPgwDiO-CBAEWyO2BoAAC0AAcopvgPwMoGgGIJbPQJkP0CAO4pWtjEVX5lBDg1I+w5wwFi6apdvaNXpbKNY2yPvW44HR44jt41RKHQfSSUE5HU-Z40oEEw-YfZTdFDE0ndaGE7rFNN-UDKmbUUE9wXVjLNtNtNIAAMrsixi0DsjRxSgaABCOOYOyN6PuwABShTyQEAUc3gxAGgvwkc4oEmGccAPIAAhKYNw-ChNE4MMARSUNIAAGTTPrCdMwDdPib6DhwX2ZzDPSAlB+IVBarLN9NwBrOtBIhooigkBuDiMZxFwogMP+KqZRKtO8jVBDPmBsMcMijhD2NlPKAzxRB7OrPIYwBHMBAnNnMXMyLAQ3NFRtpRJRAPPbjSDPOONvMfPYNfOfxQJRJ-P9OHMlDHMGCnNjBgtXP0CQvhjQswuwttNPMbOvOcMosOPosUuYu9P-MNxAsVj4uguXMQtbFP5ktapMtPhUsIs0tbzItowMs-NMtYsHMAvssguEvcvXO8uVx3OCu1xwvUsvNit0sStotSuCsys4ujMcsEvnNKsksqt3xqvqsavCuIu0vvN6vlOMu2swtMOAudK2tlLetesws+v+t+sBtlKsDKC4TksevTbWAq2Uh4j+BhBsAcAgCYA4B4DZD9OUA0D0AsiiA8BsDZxUDCjchICoDJtcB4C0DqAwDUAGMCDwqSDkA8AkDEBqBwCID5P+BqBzAijZC0BYDbRYCjDYPQAAACak+A47splbqj20071btbmbHTvweA-A+brAQAA), cheating a bit so that the legacy definitions cause the events to fire in the browser the way they fire with the mocks.

I've also enabled `preventDefault()` for (not) toggling checkBoxes (the only default action the mocks support).

----

I like @spacejack's proposal, I had something similar in mind. You need an option object, just strings as with @isiahmeadows's last proposal wouldn't work because `touchstart` and `touchmove` default to `passive: true` in recent Chrome (an Web-breaking abomination if you want my opinion, but they did it nevertheless).

@tivac, without arrays (and unless you rely on hooks) you can't define distinct handlers for both phases on a single element.

re. necessity it would be nice to have IMO. Options are supported in all evergreen browsers now.

**Pull request merged**
