### PR TITLE
Move the chat to Zulip

### PR DESCRIPTION
**Pull request by pygy**
This updates the links to the new chat. Please don't merge, I'll do it once the Zulip instance is finalized.

Also, I don't remember how we publish to mithril.js.org...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation change

### CODE REVIEW

**Comment by StephanHoyer** [comment]
thanks @pygy 

will check later. lgtm so far

**Comment by pygy** [comment]
@StephanHoyer I've left the "gitter-logo.png" file alone for now. I don't know if we can reuse it for Zulip. There doesn't seem to be a way to use a non-zulip logo in the top-left

**Review by dead-claudia — APPROVED** [review]

**Comment by pygy** [comment]
@dead-claudia how do we publish the changes to mithril.js.org?

**Comment by pygy** [comment]
Uh oh... Should I have tagged the commit message differently? PR-release wants to do a patch-release now...

**Comment by pygy** [comment]
Actually, a release is needed to update the README over at npm

**Pull request merged**
