### PR TITLE
Fix Stream.end()

### PR DESCRIPTION
**Pull request by charlag**
As discussed in https://github.com/MithrilJS/mithril.js/issues/2365
Stops calling dependent function and reduces memory leaks.
Also fixes container semants for ended streams.

## Description
Removing dependent function and stream when the child ends. This restores old (correct) behavior. Before, ending child stream would keep it and it's function in a parent and that function would be called.
Also fixed container semantics for ended streams: they will still change their value now.

## Motivation and Context
Maintaining correctness of parent-child relationship and preventing memory leaks for keeping children and their functions.

## How Has This Been Tested?
I've added two new tests (for `map` & `combine`). For other functions semantics shouldn't change, but memory impact may improve (`merge` would be GC'd e.g.). 
I've also added test for stream working as a container in the ended state.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I have updated `docs/change-log.md` (no need to)

I'm not sure that I understood the proposed fix for container semantics but I think mine works too.

There's one open question regarding the end stream (the open obtained by `stream.end`, not "ended stream"). Who ends the end stream? Each stream has a co-dependent `end` stream, event the `end` stream itself. An attempt to close it will continue infinitely. I'm not sure it's needed, I don't think it's mentioned in docs but I wanted to raise this question anyway, as it seems to be related.

### CODE REVIEW

**Comment by isiahmeadows** [comment]
@porsager Since this is reverting a small bit of your patch, could you take a quick look at this?

**Comment by porsager** [comment]
Oh yeah, that are quite some oversights actually. Good job describing and fixing @charlag !

I do see another way of fixing the issues with less orchestration if we are ok with the dependent stream not being removed until the next time a parent tries to write to it.

Changing streams to this:
```
	function stream(v) {
		if (arguments.length && v !== Stream.SKIP) {
			value = v
			if (open(stream)) {
				stream.changing()
				stream.state = "active"
				var i = dependentStreams.length
				while(i--) {
					dependentStreams[i].state === "ended"
						? (dependentStreams.splice(i, 1), dependentFns.splice(i, 1))
						: dependentStreams[i](dependentFns[i](value))
				}
			}
		}

		return value
	}
```

and adding 
```
if (stream.state !== "ended")
	stream(fn.apply(null, streams.concat([changed])))
```
to combine should do it.

It seems like a smaller/less invasive change

**Comment by charlag** [comment]
@porsager  good job rewriting it, it is a very straightforward implementation.

I have considered removing them lazily but was reluctant because it's less predictable memory behavior. I don't have a strong opinion on this.

I'm a little but worried that you modify the array while iterating it though.

I also don't quite understand how we will end mappers with proposed solution for `combine`. It seems to be semantically correct but will leak some memory it seems (or am I wrong here?).

**Comment by porsager** [comment]
Thanks @charlag 

I think you're right wrt. memory. No reason to have them hanging around potentially forever. 
And you're also quite right about combine. It would need to be removed from `streams` lazily there too for the entire thing to work.

Let's move on with your solution 🙂 👍 from here...

About modifying the array while looping, it's not an issue as long as you're looping backwards 😉

**Comment by charlag** [comment]
Thanks for reviewing it!
Yes, you're right, it works with iterating backwards, didn't understand at first. I just try to avoid indexing into array anyway :stuck_out_tongue:

**Pull request merged**
