### PR TITLE
ES6 and m.trust docs patch

### PR DESCRIPTION
**Pull request by kczx3**
## Description
While reading through some of the documentation I saw some issues with both the ES6 and `m.trust` pages.  The ES6 page uses the dollar sign wrapped in backticks which causes an issue due to the usage of `String.prototype.replace` in `scripts/generate-docs.js`.  As for `m.trust`, a closing BODY tag was sneaking through to the html.  I just wrapped that code piece in backticks which resolved that.

## Motivation and Context
Saw an issue and easy enough to fix myself and provide an option for resolution.

## How Has This Been Tested?
I ran the tests although it did fail on `test:js` which I'm not sure why.  I didn't touch any of what that would be testing.

```
> mithril@2.0.4 test:js C:\Users\<user>\projects\mithril.js
> node ospec/bin/ospec


the done parser > tolerates comments:
true
  should equal
false
    at C:\Users\<user>\projects\mithril.js\ospec\tests\test-ospec.js:715:12

––––––
1 out of 14124 assertions failed in 3808ms
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation change

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have updated `docs/change-log.md` (wasn't sure if this was necessary or not)

### CODE REVIEW

**Comment by isiahmeadows** [comment]
Have you built the documentation and verified the output? (The main tests themselves are irrelevant as you didn't modify that code.)

**Comment by kczx3** [comment]
Uh, yeah... that’s how I verified that the changes I made worked... granted, I only checked the output of those two html files because I only modified their respective markdown files.

**Comment by isiahmeadows** [comment]
@kczx3 I was asking because the initial comment didn't state that in the "How Has This Been Tested?" part.

Your limited testing is sufficient, though - I was just looking to make sure the fix was verified first.

**Comment by kczx3** [comment]
Good deal. Sorry if that was a bit passive-aggressive. Thanks and glad I could make a small contribution.

**Comment by isiahmeadows** [comment]
No problem! Also, apologies if I came off similarly. 🙂

**Pull request merged**
