### PR TITLE
issue #1914 docs/support.md should exist

### PR DESCRIPTION
**Pull request by thepriefy**
## Description

As discussed in #1914 , both CONTRIBUTING.md and SUPPORT.md should be in ./.github folder.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have updated `docs/change-log.md`

### CODE REVIEW

**Comment by tivac** [comment]
I just tested, and `./docs/contributing.md` is correctly picked up by GH on the new issue page.

https://github.com/MithrilJS/mithril.js/issues/new

image

Given that, we should put this file in at `./docs/support.md` after all. Sorry for the bad advice, @thepriefy 😞

**Comment by pygy** [comment]
@tivac: @thepriefy added then removed `.github/CONTRIBUTING.md`. The file in `docs/` is safe and sound.

**Comment by tivac** [comment]
Yeah, I should've looked more closely.

That said, my second point stands. This file should be in `./docs/support.md` and I bet that'll work fine.

**Comment by pygy** [comment]
🤞

:-)

**Comment by thepriefy** [comment]
@tivac That's fine. I don't mind changing some requirements. 
BTW, I have already changed the folder name of support.md file and I have already had I commit which delete my own contributing.md file (in .github folder).
If there is anything you want to change or there is any prpblem, feel free to tell me. :)

**Comment by pygy** [comment]
Success!
screen shot 2017-12-04 at 01 01 09

**Comment by pygy** [comment]
Thanks @thepriefy

**Pull request merged**
