### PR TITLE
Update render.js

### PR DESCRIPTION
**Pull request by RohitPaul0007**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have updated `docs/changelog.md`

### CODE REVIEW

**Review by dead-claudia — CHANGES_REQUESTED** [review]
Please fill out the form. You didn't even check a single box in the checklist. Also, we do try to maintain limited IE support, and our current build system doesn't do `let`/`const` -> `var` conversion.

If you want to attack the bigger step of moving us to modern ES, go for it, but it won't be as simple as just this. Also, please bundle all of the work into just a single pull request.

(If this was discussed on Zulip and I'm wrong here, please let me know so I can dismiss my review.)

**Comment by boazblake** [comment]
This guy is spamming a bunch of repos with the same changes. 


https://github.com/RohitPaul0007/tween.js/pull/5/commits/e892ed82618687d3fcc5a99c3733d2b6da723823

**Comment by dead-claudia** [comment]
> This guy is spamming a bunch of repos with the same changes. 
> 
> 
> https://github.com/RohitPaul0007/tween.js/pull/5/commits/e892ed82618687d3fcc5a99c3733d2b6da723823

Would like to give some benefit of the doubt, just in case they decide to engage in good faith.

Not surprised, though.

**Comment by asturur** [comment]
> > This guy is spamming a bunch of repos with the same changes.
> > [RohitPaul0007/tween.js@e892ed8](https://github.com/RohitPaul0007/tween.js/commit/e892ed82618687d3fcc5a99c3733d2b6da723823)
> 
> Would like to give some benefit of the doubt, just in case they decide to engage in good faith.
> 
> Not surprised, though.

is a spammer, i have the same issue with him. I also blocked him but he can continue to opens pr regardless

**Comment by RohitPaul0007** [comment]
> For what it's worth, some of my leniency is because a few of my first open source contributions were similarly garbage quality (to be fair, I was still in high school at the time and had almost no clue what I was doing).

thanks

**Comment by JAForbes** [comment]
Should we close this?

**Comment by dead-claudia** [comment]
@JAForbes Sure. I was just keeping it open 1. to make my point and 2. in the off chance they decided to revisit their change and pack it all into one PR.

**Pull request closed without merging**
