### PR TITLE
Remove lifecycle attr support for component vnodes

### LINKED ISSUE #1775: Lifecycle methods passed to component called twice ?
Please see https://jsfiddle.net/dhtn0zg4/2/

Output1 tests vnode's lifecycle methods and onclick event handler.
Output2 tests component's ones.

It seems that oncreate and onupdate functions passed to component are called twice.
I expected to see "oncreate out of component called." first (because it's passed to vnode in component.) then "oncreate in component called.".
But "oncreate out of component called." is displayed once more.

Is it bug or is there the solution to avoid this ?
Thank you.

### LINKED ISSUE #1986: "Avoid restrictive interfaces" docs section hits its own gotcha...
## Expected Behavior

A correct set of docs...

## Current Behavior

In the ["Avoid restrictive interfaces" section of the component docs](https://mithril.js.org/components.html#avoid-restrictive-interfaces), it offers the advice to send `vnode.attrs` directly to the component. This is bad because [it can result in vnode lifecycle hooks being fired more than once](https://github.com/MithrilJS/mithril.js/issues/1775), and nobody expects that.

## Possible Solution

Three options:

1. Use my [`censor` helper](https://github.com/isiahmeadows/mithril-helpers#mithril-helperscensor) in the docs
2. Move my helper to core and use it in the docs
3. Ignoring lifecycle hooks from vnodes with identical `vnode.attrs` to the component's received `vnode.attrs` during rendering.

The last point IMHO is probably the best of the lot, although it doesn't catch the case of `{...attrs}`. In the latter case, they can still use the `censor` helper to remove lifecycle hooks before adding their own things.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

See my [`mithril-helpers/censor`](https://github.com/isiahmeadows/mithril-helpers#mithril-helperscensor) docs, which also explain this. (That was also the driving reason for the library in general.)

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

### PR DESCRIPTION
**Pull request by isiahmeadows**
## Description

I removed lifecycle support from component vnode attributes.

## Motivation and Context

See discussion in #2219 starting [here](https://github.com/MithrilJS/mithril.js/pull/2219#issuecomment-425233119). This PR should be considered as an alternative to it.

Fixes #1775
Fixes #1986

## How Has This Been Tested?

Ran all the usual tests and perf benchmarks. I ripped out newly redundant tests and assertions, but the rest still pass. Performance is solidly within the margin of error.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have updated `docs/change-log.md`

### CODE REVIEW

**Comment by isiahmeadows** [comment]
I review-requested everyone who was active in #2219, since this is an alternative solution proposal to that problem.

Once one of them gets merged, I'll cut a v2.0.0-rc and see if anything breaks.

**Comment by cavemansspa** [comment]
@barneycarroll -- aiui, the change results in the following behavior:

```
const Input = {
  oncreate: (vnode) => {},  // this will still trigger
  view: ({ attrs : {
    name,
    inputAttrs,
  }}) =>
    m('label', 
      name, 
      
      m('br'),
      
      m('input', inputAttrs),
    ),
}

m(Input, {
  oncreate: (vnode) => { } // used to trigger, but will NOT trigger with this PR
})
```

which seems reasonable, no?

**Comment by isiahmeadows** [comment]
@barneycarroll 

> I'm not keen on this resolution. The ability to attach lifecycle behaviour to components is extremely powerful: we shouldn't take this out in order to partially mitigate the headaches of generic interfaces where attributes are passed wholesale to multiple nodes — this would remove a feature in order to encourage bad practice.

[There's a second reason, too](https://github.com/MithrilJS/mithril.js/pull/2246/files#diff-54b1aec2920e68d6f195d88664bddaa5R116), one that plenty of others have mentioned in the past, especially in Gitter: `oncreate`, `onupdate`, and `onremove` are often the perfect names for certain operations, but because Mithril has magic treatment for them with components, you start seeing very odd-looking workarounds like `onCreate` and similar, which *really* doesn't fit with the usual idiomatic preference of lowercase event names (typical of DOM and magic event handlers).

And FWIW, the workaround I recommended in the docs, primarily only useful for Meiosis users (who don't use components), is this:

```js
// v1
m(Input, {
  oncreate: (vnode) => { },
  ...
})

// v2 + this PR
m.fragment({
  oncreate: (vnode) => { }
}, m(Input, {
  // ...
})
```

And in general, this is a pretty rare need at the fragment level outside components.

**Comment by spacejack** [comment]
IMO this is too specific of a fix. I think it's easier to learn that lifecycle names are always reserved in attrs rather than just in some cases.

**Comment by isiahmeadows** [comment]
What about the alternative, #2219?

(I think that's the issue number...I'm typing this from my phone, not
through GH.)

**Comment by spacejack** [comment]
> What about the alternative, #2219?

I agree with @barneycarroll again on that issue - I'd rather see the docs updated.

FWIW I'm pretty much going to :-1: every API change suggestion for v1.x-v2.0.

**Comment by isiahmeadows** [comment]
Okay, will do.

**Comment by StephanHoyer** [comment]
This and also #2248 suggest to have some kind of develop build that does additional checks and give warnings or even throws errors, when doing stuff that's dangerous or not idiomatic.

This probably requires to change the bundler though.

**Comment by isiahmeadows** [comment]
Closing - we decided against this route.

**Pull request closed without merging**
