### PR TITLE
Fix issue #1798

### PR DESCRIPTION
**Pull request by jonahx**
https://github.com/lhorie/mithril.js/issues/1798

### CODE REVIEW

**Comment by isiahmeadows** [comment]
Could you add a test case that confirms this actually fixes stuff?

You could do it by temporarily overriding `console.log` and expecting certain output.

**Comment by jonahx** [comment]
Yes, no problem.  But probably won't be able to get to it till later in the week.   Meanwhile, what are your thoughts on the question I brought up in the final paragraph above?

**Comment by isiahmeadows** [comment]
@jonahx I'm for preventing string errors in ospec, but I'd rather you file a separate issue for discussing that, so we're keeping the noise level down. It'll also have to go through the other collaborators to verify that's what we want.

Also, keep in mind, [I'm not nearly as invested in ospec as the other contributors are](https://github.com/isiahmeadows/thallium).

**Comment by jonahx** [comment]
Closing this until I can add tests.  Also while it's better than the current behavior, it's still not correctly reporting the error, I just realized.

**Comment by isiahmeadows** [comment]
It still fixes another issue (thrown strings), so let's leave it open.

**Pull request merged**
