### PR TITLE
[ospec] Add the possibility to name new test suites

### PR DESCRIPTION
**Pull request by pygy**
I'm using ospec in a monorepo setting with a single test runner for the whole project. I'd like to have per module test stats that can be identified more easily. Currently, only the number of test appears, with the PR, it would become `$suiteName: 385 assertions completed in 122ms, of which 0 failed`.

Suggested use:

```JS
// modules/foo/test-utils/ospec-instance.js
var o = require('ospec')
var instance = module.export = o.new('suite name')
o('suite name', instance.run)
```

Then, in each test file of a given module, replace `require('ospec')` with `require('../test-utils/ospec-instance')`.

### CODE REVIEW

**Comment by pygy** [comment]
@lhorie had this any chance of getting merged?

**Comment by isiahmeadows** [comment]
Closing, since this issue has not been updated in over a month, and typically, issues inactive for that long do not usually produce any action. If you feel something in Mithril needs added or changed, please file a new issue.

**Comment by pygy** [comment]
I actually would like to have this merged...

**Comment by isiahmeadows** [comment]
@pygy Could you add tests, then? Also, `name` is never set.

**Comment by pygy** [comment]
I'll have to look at how to test this... It's not trivial. It manifests itself through STDOUT, the state is private.

`name` is set by calling `ospec.new("some name")`.

**Comment by isiahmeadows** [comment]
Oh. I'm not well versed on ospec's API, and only know just enough to pass (I use either Mocha or [something else entirely](https://github.com/isiahmeadows/thallium)).

**Comment by tivac** [comment]
This seems pretty useful, and a very small change. I'm in favor. @pygy if you fix the conflicts we should merge this unless @lhorie disagrees.

**Comment by pygy** [comment]
Conflicts fixed (there were none, really, the changes were on different lines, dunno what prompted them in the first place)... Merging!

**Pull request merged**
