### PR TITLE
Fixed a punctuation error

### PR DESCRIPTION
**Pull request by mikeshatch**
## Description

**Changed:**

Javascript ==> JavaScript

## Motivation and Context

Punctuation error. Please note: The same error exists in the description area.

### CODE REVIEW

**Comment by mikeshatch** [comment]
> If you're going to fix one, why not fix both occurrences?

Hi @isiahmeadows. I would if I knew how. You can't do it via the README file. Which file do I look for?

**Comment by isiahmeadows** [comment]
Go to your fork, go to your patch's branch, click the README file in it, and click "Edit". That will let you edit, and you can commit from there.

**Comment by mikeshatch** [comment]
Thank you. The Edit button doesn't show until after you've forked it. It's now edited.

**Comment by isiahmeadows** [comment]
@mikeshatch Are you sure? I don't see the new change here.

**Comment by isiahmeadows** [comment]
Found a few more occurrences, if you'd like to take a stab at them all: #2398

**Pull request closed without merging**
