### PR TITLE
[ospec] Make the default reporting nicer looking

### PR DESCRIPTION
**Pull request by maranomynet**
I thought the default reporter could be made to look nicer, using more colors, a divider and slight indenting of the `verb` ("should equals" etc) and some rewording of the final result message.

## Before 
screen shot 2018-05-11 at 00 02 30
screen shot 2018-05-11 at 00 03 04

**Browser:**
screen shot 2018-05-11 at 00 13 08
screen shot 2018-05-11 at 00 14 20

## After

**Update:** See **[below comment with updated screenshots](https://github.com/MithrilJS/mithril.js/pull/2147#issuecomment-388315182)**

screen shot 2018-05-11 at 00 01 29
screen shot 2018-05-11 at 00 00 32

**Browser:**
screen shot 2018-05-11 at 00 11 26
screen shot 2018-05-11 at 00 14 40

## How Has This Been Tested?
Ran tests in node and pasted representative `console.log` and `console.error`strings into the developer console of Chrome and Firefox. (See screenshots below.)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have updated `docs/change-log.md`

### CODE REVIEW

**Comment by maranomynet** [comment]
Someone should tell @Gandalf-the-Bot to accept change to **any** change-log.md file - not just the mithril.js one. 😄

**Comment by pygy** [comment]
I agree there's room for improvement on the output format, but cyan stack traces on a white background (e.g. with the default macOS Terminal.app) don't [meet the WCAG AA guidelines](https://webaim.org/resources/contrastchecker/?fcolor=00BECC&bcolor=FFFFFF).

screen shot 2018-05-11 at 09 36 24

I'm less concerned about the green text because there's little to read, but for the stack traces this is problematic.

The light red is actually a bold red in Terminal.app, so it is fine too AFAICT.

**Comment by maranomynet** [comment]
Good point, and interesting to see Apple making that choice.

So instead of the cyan we could use `34;1m` bright blue (because dark-blue suffers the same lack of contrast on black background) or `35m` magenta (or bright magenta).




All of those would work.

Bright cyan, however, becomes too aggressive IMO on dark background and demands all the attention

**Comment by maranomynet** [comment]
Here are the new color suggestions:

screen shot 2018-05-11 at 09 40 12
screen shot 2018-05-11 at 09 39 46

**Comment by maranomynet** [comment]
I've been using this version locally in some projects, and I find it to be a _real_ improvement over the current reporting.

**Comment by tivac** [comment]
I have no opinion, I don't use ospec much if ever these days. Seems fine in the abstract.

**Comment by barneycarroll** [comment]
Been using it masses recently but mainly for quickly validating Mithril patches where I was scared of cross cutting concerns so didn't use this branch. Give me a while to throw it for a spin? Looks gorgeous BTW.

**Comment by pygy** [comment]
@barneycarroll I'll merge this now, we can tweak it later if needed.

**Pull request merged**
