### PR TITLE
Fix Content-Type header bug (Issue #1919)

### LINKED ISSUE #1919: Setting the Content-Type header in POST requests do not overwrite default header
If you make a POST request and set the Content-Type header, it will not overwrite the default Content-Type header but rather will get appended to the default header. This does not happen in GET requests. I have not attempted this with any other types.

## Expected Behavior
The expectation is that setting a header in POST requests actually means setting the header, rather than appending to some default header.

## Current Behavior
The Content-Type header set by the user will get appended to the default header

## Steps to Reproduce (for bugs)
Look at the network tab for the below fiddle after running, you'll see the POST request made by the code and see that the Content-Type header is not what the user set it to.
Repro: https://jsfiddle.net/2bmk0zjs/2/

### PR DESCRIPTION
**Pull request by tskillian**
Fixes #1919

### CODE REVIEW

**Comment by botvac** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please add an entry to <a href="https://github.com/tskillian/mithril.js/blob/fixRequestContentHeaders/docs/change-log.md">docs/change-log.md</a>.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by pygy** [comment]
@tskillian That's great, I see you've updated the mocks (the existing tests in `request/tests/test-request.js` were correct assuming proper mocks), it would be nice if you could add some mocks tests as well in `test-utils/tests/test-xhrMock.js`.

**Comment by tskillian** [comment]
@pygy done

**Comment by pygy** [comment]
Beautiful, thanks :-)

**Pull request merged**
