### PR TITLE
Fix some linter issues, update ESLint

### PR DESCRIPTION
**Pull request by isiahmeadows**
## Motivation and Context

~~Having two exports is pretty redundant - you're only saving 2 non-whitespace characters by using a default export. Also, I fixed some linter issues I ran into.~~ **Edit:** Noticed that our local ESLint version was outdated and that there were a few odd things missed. I also ran `npm audit fix` as a drive-by.

Saving the module changes for later once I have some bundler support.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have updated `docs/change-log.md`

### CODE REVIEW

**Comment by isiahmeadows** [comment]
Also, I ran `npm audit fix` on it to resolve a few problems.

**Comment by isiahmeadows** [comment]
@porsager Ours is easy: we just export multiple things. If we export multiple things and we do so consistently, nobody will ask. We'll just need to document the ESM API being different than CommonJS due to idiomatic differences.

**Comment by porsager** [comment]
But doing both we don't have to document anything?

**Comment by isiahmeadows** [comment]
@porsager I'm considering reverting the ESM change in favor of just updating the bundler to work with ES modules (I'm 99.99% it's possible to do surgically.)

**Comment by isiahmeadows** [comment]
Edit: I'm going to go ahead and keep this strictly limited to linting.

**Pull request merged**
