### PR TITLE
Moving to UglifyES for minification

### PR DESCRIPTION
**Pull request by CreaturesInUnitards**
## Description
Ripped out all the Closure Compiler stuff, and replaced with the much-simpler UglifyES.

## Motivation and Context
This solves a tiny part of the "@isiahmeadows, @pygy and @barneycarroll don't have time to do absolutely _everything_" problem.

## How Has This Been Tested?
All the existing tests pass. This is a feature replacement, not an enhancement or a true "fix", therefore new tests should not be needed.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Feature replacement (non-breaking change which uses a now-preferred approach)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I have updated `docs/change-log.md`

### CODE REVIEW

**Comment by isiahmeadows** [comment]
BTW, this has been on my TODO list for a while.

**Comment by CreaturesInUnitards** [comment]
If you feel like enumerating the missing bits of your preferred overhaul, I’ll happily take a crack at them.

**Comment by isiahmeadows** [comment]
@CreaturesInUnitards Mostly just returning a value from `minify` and making [all this stuff sync](https://github.com/MithrilJS/mithril.js/blob/6ecbf85ccc06cdbfb0d8193ad8731f40cb94c5ec/bundler/cli.js#L29-L48) (obviously with a `!= null` check).

**Comment by CreaturesInUnitards** [comment]
fuhgeddaboudit. I re-did this, but betterer.

**Pull request closed without merging**
