### PR TITLE
Release v2.1.0

### LINKED ISSUE #1759: Add docs for cancelling route resolution
It is a common use case to want to check that certain conditions have happened before allowing for route changes.

Example: a page with a form but also links to other pages, the form data has a flag for unsavedChanges and you do not want to allow route changes but actually want to display some UI to alert the user of these unsaved changes.

### LINKED ISSUE #2398: "JavaScript" is inconsistently capitalized
[Throughout the docs](https://github.com/MithrilJS/mithril.js/search?q=Javascript&type=Code), I'm only seeing "JavaScript" capitalized in two ways, both incorrect:

- "javascript"
- "Javascript"

Out of that entire search, only the occurrences in the code block language tags and the MDN URL are correct - everything else needs fixed.

-----

This is an easy bug to fix, so if you want to file a patch, feel free to do so. We've already got #2397 to kick it off. And it'd make a good first pull request as you don't really need to get into code much.

### LINKED ISSUE #2472: Add a core utility to strip magic keys and other keys from a component
**Mithril version:**

**Browser and OS:**

**Project:**

**Is this something you're interested in implementing yourself?** Yes

### Description

Continuation of https://github.com/MithrilJS/mithril.js/issues/1986

Specifically, I'm suggesting bringing in [this utility](https://github.com/isiahmeadows/mithril-helpers/blob/master/censor.js) into core. Already just got bit writing a built-in utility, and I know not everyone reads the docs closely. Plus, having a core utility that contradicts [this](https://mithril.js.org/components.html#don't-forward-vnodeattrs-itself-to-other-vnodes) doesn't really make sense, and I don't expect everyone to read the docs closely enough to pick this up. So instead, we should just provide a built-in utility to strip all that crap out *for* people.

### Why

Well, if you want to know how easy it is to get bit without realizing it, take a look at #2471.

### Possible Implementation

https://github.com/isiahmeadows/mithril-helpers/blob/master/censor.js with the alterations needed to fuse into core. (It's 324 bytes min+gzip standalone.)

### LINKED ISSUE #2552: npm package contains a lot of unnecessary things
I have no idea if this was intended or not (I hope it was not), but `node_modules/mithril/dist/` takes 18M, mostly because of `archive` being there (with lots of `*.md` and `*.html` files)

You can verify easily here `https://unpkg.com/browse/mithril@2.0.4/dist/archive/`

### LINKED ISSUE #2597: something strange in the updateNodes code
https://github.com/MithrilJS/mithril.js/blob/cf7a841c4ce68989ff49a5c794e076d3defd1a0a/render/render.js#L280-L285

The last line will never be true

### LINKED ISSUE #2601: Mithril stream.end(true) ends other dependent streams as well
**Mithril version: 2.0.4

**Browser and OS:** Windows 10, Chrome Version 83.0.4103.61

**Project:**

[mithril stream](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIATjDCy4hCGgDmkgLySs+CbOwAKAJQAdNKfFTaARg0y5CpavxYMAB30A3DQD5J7gOTWdtQwEB4wACb+FJIehiZmaBaSAO4YEMTKapqy8vCOKs5u+p4YUIY+ksCmkn76-mkZWcGh4VExHmUJtRBgkqVQGuqaYGVwMBXVaLW1jZlOTBH6xNIArhM1MwFzzYuR-t2SrKasCeb0EpK0AEy2uQ5ZRe5e6r4BNy1h+x3xpqb3+SyyzWGzQAMUQNGUHGCXBBXqWFosgOpkoNFoWFc0Bg0jwACMMHiYOQqONYNRMhc8FYAOyIAAMbA4IEwODw+GocAE6OEzB4bAAulQoMoANYIFCcNk8LAZQjSaBo1bScg8EjEVxwRAAem1qzQrlFhToWG1suI8ugAAFrvh6fgACxmuUKqDOZT4fho4gAT1c3BAcGoCtconYUoD5stUAAtLoYNglSq8OrNTq9QajRyMc6La64ysE1gbXa7dr49hPdzff68EGQ2GBawgA) vs [flyd stream](https://flems.io/#0=N4IgtglgJlA2CmIBcB2ArAGhAMwggzsgNqgB2AhmIkiAHQBWhWAxgPakAu8nyIbp+DgAIATvGxj8ACwikA5kIC8Q7LACeUWoLGUAFAEoAOqWP9BQ1gEYlo8ZJnzaYcgAddANyUA+IW4DkVrbM8BDu8FB+GELu+kYmpGbCAO7kEByyCspiEvDSGU6uuh7ksPreQsDGQr66filpGUEhYRFR7iVx1RDYQsWwSorK2CX48GWVpNXV9emO3FC6HCIArmNVU-4zjfPhfp1CAL7GB3Gm7OasAEw22fb5zm6eij7+V02hu22xxsa3uQ5yRYrNakP55eS6YawUZxMEA2pgVhiPbGEAHAC6WFgsgA1oQkCQQBQqLxVBoQFhliJYLwpBwOC58EgAPTM5akFw4uS0NhgZlkqAAAQADLRLrQABz89SaRgUkAcNQuaggfDMEQQFwcNHog5AA)

credit to @foxdonut for the reproduction

notice in the mithril example how o2 doesn't receive the false value
but using the same example with flyd, o2 does receive the false value

The code I was writing was this:

```
    if (auth.refreshing()) {
      const waiting = auth.refreshing.map((val) => {
        if (val === false) {
          resolve(token())
          waiting.end(true)
        }
      })
    }
```

The unexpected behaviour i experience is that when there were X numbers of `waiting` streams the code `waiting.end(true)` seemed to end ALL of them

### LINKED ISSUE #2634: Can't finish installation with webpack because of webpack-cli 4.1 version
**Mithril version:**
2.0.4

## Steps to Reproduce
Do the installation step by step as written here https://mithril.js.org/installation.html#quick-start-with-webpack

## Expected Behavior
Proper npm start

## Current Behavior
Current installation step by step as in documentation ends in Webpack-cli error break. I had to install older version of webpack-cli.

`[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".
   BREAKING CHANGE since webpack 5: The devtool option is more strict.
   Please strictly follow the order of the keywords in the pattern.`

## Solution
I would like some note about using older webpack-cli v3 in documentation (installation) or proper instruction with use of webpack-cli v4.

### LINKED ISSUE #2647: Not able to change Content-Type
https://github.com/MithrilJS/mithril.js/blob/2b5c2f0fc6e16705bddbfe043e90eef5eb31210b/mithril.js#L1398

¿Is this a typo?

### LINKED ISSUE #2719: View render call does not respect direct attributes object modification
**Mithril version:**
2.0.4

**Browser and OS:**
Chrome Version 97.0.4692.71 (Official Build) (64-bit)
Linux Ubuntu 20.04

## Code

https://jsfiddle.net/dbo08vkf/2/

## Expected Behavior

In the code example above, Input 2 should behave the same as Input 1 when their corresponding "toggle disabled" button is pressed

## Current Behavior

When inputs (and im guess all html attributes) are supplied with an direct object instead of a fresh object with individual attributes, when one of the attributes gets updated, the render process does not respect the updated value

## Steps to Reproduce

Supply a direct attributes object to the `m()` function instead of building a new one in the view call.

## Context

(FYI I'm using TypeScript for my project, but this issue can still be observed in the example above) I'm trying to build a light wrapper around the native HTML components, while also giving the ability to make custom components with more complex use cases. And in the terms of the native HTML components, it is a lot easier to just supply an object it their constructor which is made up of their already existing attribute options instead of having to have private class values for each possible input type, then having to rebuild that object every time on render.
This is very much a code quality issue rather than a performance issue. Because it will allow me to do this
```js
view: () => m('input', this.options)
```
instead of this
```js
view: () => m('input, {
  disabled: this.disabled,
  value: this.value,
  onclick: this.onclick,
  oninput: this.oninput,
  onchange: this.onchange,
  // etc etc...
})
```
for every native wrapper

### LINKED ISSUE #2720: mithril.js.org: wrong type hint for iteeable parameters
Types hints like as `<code>Array&lt;Stream&gt;</code>` must be convertin to `<code>Array<Stream></code>`.
For example, https://mithril.js.org/stream.html#streamcombine

### LINKED ISSUE #2767: m.route.Link doesn't proxy event handler prevention
`m.route.Link` documentation misleadingly states that 

> [You can also prevent navigation by, in an onclick handler, invoking ev.preventDefault() or returning false. This is the same way you block other events, so it's pretty natural.](https://github.com/MithrilJS/mithril.js/blob/ea8094bd95ffe49ad25865cf3ace88cf365086b1/docs/route.md?plain=1#L174)

Neither of those criteria will actually prevent the default behaviour of a `Link` as they do with a simple `a`. It's a shame because this is IMO the clearest sentence in this APIs documentation, and it's false. [I wrote a little matrix sandbox to try and work out how event handling logic intersected with `Link` behaviour here, it may be useful for anyone else trying to reconcile expectations](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvWGgAgCcYaBXVtAfTAxQ4MEswA6aZlOYAHdgDd6NACIwBnKDVETpzKBjg0ASpU50AJhIlU0h5tXJQI5ANbMAvMxgeAfM2A6zBBgABTsXDz8gsL45pRY+OQAFjCuMOYAlIFS4dySAkIwVpJBoXIwirSq6pqx8YkpaZnZXvjllSpqGBo0IVloAL7FNnY0rBAA5hMwrHAezH2+zMiBWCEJrKZ0+AAyEGguogElUnQAHjQAwtR0tIjMAAYbWzC7+y5iEg8kLUnsYMx7gByAD0QOYAGpmMoMNs0JQAO59H4nexoRzOQ6BAYZFGrEJAjBAo4tc5XG5Ke4PAAK+n2zAAPBgfJ80N9fv9AcxQeCoTC4YjkS0HE5XCipDi8SU1kDzBB5MT-KSYBdrrRKY9aRh6Qy5fIWV9xdIRZijZKJABdYrPMwwEJxcicHC0fAAI0o5gAnqIeZDobDXvCkbilSVQYgZLCkvgY0D7sddNQsLDkn0E7o9AZjC9zPN+YHBf1dAMjVIWuw0OYZvdFu4-C0pDL3V7kIZPbB3GAbogAIz4ACsMCwIIATAPmFhqJQ4JHyDAANwIpIQOgAWhnGDnEfYFuJDakQJ2WbYOeYsOkiv0hhMttzUKBrL3qOk++5R7sFar7Fz58V+fwQaLPej6lror5NqwQK4q+4jPtIMr6K6MBQE+GYZrkkQFMI8wyvsMhmMgNCejIMDuMkqQuO6Zy7tBcG6OCGH5NERQSA+dHMLRaFluxCEYEhKGgWh7RKNU3SaDhBJ4QRREkWRjSUZQ1FQYJGbgsJVRdD0j4wZxaHgQSrqQbpek8QSrZER2cozvonqIBM4zmPO9kQOYq50FgMj6GuVBQE6ti9mArDMD2gW7ipYHsY2BJ6qhXG6E2ipAgAsiufzQKu7qcJWj7GXFsF5dIYyTNMsxCpFHHhS+5UyjFlXxQZiVJRgaCcIIUCehlpjZaxuVxTBiaKKwDl2r1XFFVMMxwGVBU5PANCUOw015aNUijbpQyDP01jUHYvBYDhxRgFl5A0BA1D2INw1pqs8wAPKuoQqQ0PgBhwJMaAhC0IQ0BgEyiLCYxwKIMb4OwhgZEs6a6ME33ETAlAAgDsweO4nhApQD1PeCABk2PMAAhEjcD4PIEAwAiGRQxmIwsFJLCeMAINExtfXsUT8xU2hDjsAGITyJT-XSPdj0nS9cBvRMH3yHUWCiHTRZ5SzXFK8W+77oxzB7d9v3-TQgPAzGYM0ArEpGi0suBP0G0SEd6KnedRsLSN6b7Z4e0SAMIBkMIsAnWdth4P2iAjj2JAABzBwAzCAAwWmQTgHAgKDoNguCICAWCpeMUBeyA3A5+nSR6zIcCICCIJZTILgTIk8QgpnNBpVAAACY4AAz4AALPXWfQPgmdoEQpAgDJacgHA5DjDINAxxaAxAA).

It took me reading the [source](https://github.com/MithrilJS/mithril.js/blob/ea8094bd95ffe49ad25865cf3ace88cf365086b1/api/router.js#L205-L273) & returning to read the docs a few times over to realise they're trying to explain the behaviour of a special-cased magic `disabled` attribute, which is the only way of preventing an `Link` from resolving. On that front, they're extremely unclear. Critically, the published docs have a typo stating that [the `disabled` attribute is forwarded to the `m.route.set` API](https://github.com/MithrilJS/mithril.js/blob/ea8094bd95ffe49ad25865cf3ace88cf365086b1/docs/route.md?plain=1#L212).

### PR DESCRIPTION
**Pull request by JAForbes**
# Release v2.1.0

<a name="changeSummary-start"></a>

- #2769
- #2752
- #2768
- #2578
- #2722
- #2316
- #2750
- #2711
- #2743
- #2670
- #2695
- #2641
- #2655
- #2537
- #2646
- #2633
- #2594
- #2603
- #2539
- #2536
- #2405
- #2744
- #2765
- #2760
- #2758
- #2751
- #2757
- #2748
- #2745
- #2620
- #2644
- #2649
- #1767
- #2718
- #2693
- #2741
- #2651
- #2721
- #2353
- #2206
- #2648
- #2672
- #2717
- #2348
- #2698
- #2696
- #2684
- #2680
- #2679
- #2673
- #2674
- #2657
- #2639
- #2487
- #2585
- #2630
- #2629
- #2628
- #2627
- #2608
- #2605
- #2593
- #2582
- #2576
- #2573
- #2567
- #2561
- #2553
- #2540
- #2538
- #2522
- #2513

<a name="changeSummary-end"></a>
        
## Changelog

<a name="changelog-start"></a>
#### [m.censor: work around a bunder bug (@kfule)](https://github.com/MithrilJS/mithril.js/pull/2752)

The internal bundler sometimes mangles the words in RegExp literals incorrectly.  Please see below.
#### [Send URLSearchParams as request body without extra configuration (@Coteh)](https://github.com/MithrilJS/mithril.js/pull/2695)

This PR fixes an oddity I noticed in the way `m.request` handles `URLSearchParams` object.  It now handles it in the same sort of way XHR and Fetch do it.
#### [Add `params:` to `m.route.Link`, fix docs (@dead-claudia)](https://github.com/MithrilJS/mithril.js/pull/2537)

Add `params:` to `m.route.Link`.  Minor fix to docs to reflect reality with `m.route.Link`'s `disabled:` attribute.
#### [Allow Mithril to be loaded in non-browser environments without modification (@dead-claudia)](https://github.com/MithrilJS/mithril.js/pull/2633)

Recast the global reads to all be guarded with `typeof`, so that if they aren't defined, they're just `null`.
#### [Add a `m.Fragment = "["` utility for JSX users. (@dead-claudia)](https://github.com/MithrilJS/mithril.js/pull/2744)

The title says it all, and the diff's obvious.  Resolves https://github.com/MithrilJS/mithril.js/issues/2640 and probably others.
               
#### [Enable --minimize-semver-change for pr-release (@JAForbes)](https://github.com/MithrilJS/mithril.js/pull/2769)

Minimizes semver changes on release to the minimum required version bump to satisfy major/minor/patch semver ranges.  Minimizes the semver change so that.
#### [Clean up m.route.Link (@barneycarroll)](https://github.com/MithrilJS/mithril.js/pull/2768)

An attempt at better demonstrating `m.route.Link` with less text.  Fixes #2767.
#### [Runtime-deprecate ospec, change `change-log` to `changelog`, fix a few assorted bugs (@dead-claudia)](https://github.com/MithrilJS/mithril.js/pull/2578)

This PR is in two parts: 1.  Revise the build system and some of the local dev setup.  Fully split ospec from the repo, and add it as a dependency.
#### [Add meta description to docs (@StephanHoyer)](https://github.com/MithrilJS/mithril.js/pull/2316)

rework of #2149.  added a meta description parser and meta descriptions to all docs pages.  because google.  built the docs, inspected the output manually.
#### [Fixed badges, consistent naming of Mithril.js (@tbreuss)](https://github.com/MithrilJS/mithril.js/pull/2750)

use consistent naming of Mithril.js.  fix badges in README.  Fixes issue #2749.
#### [Catch malformed URI Components (@jdiderik)](https://github.com/MithrilJS/mithril.js/pull/2711)

Fix for error thrown when a value contains non-valid / malformed URI Component.  Example: test=%c5%a1%e8ZM%80%82H.  will throw "URI malformed".
#### [Correctly handle invalid escapes in routes based on 0a5ead31c9fbd7b153c521c7f9d3df7bf826ce6c (@StephanHoyer)](https://github.com/MithrilJS/mithril.js/pull/2743)

fixes #2061.  @dead-claudia I just redid your change but slightly different in order to handle a mix of wrong and right encodings properly.
#### [Standardise vnode text representation (@barneycarroll)](https://github.com/MithrilJS/mithril.js/pull/2670)

This addresses the crucial feature of #2669: text is always represented as virtual text nodes, never as a `vnode.text`.
#### [Issue 2624 no content 204 parse (@Evoke-PHP)](https://github.com/MithrilJS/mithril.js/pull/2641)

Added guard so that JSON.parse does not fail on IE11 with no content empty string being parsed.  Fixes https://github.com/MithrilJS/mithril.js/issues/2624.
#### [[m.request] work around a bundler bug, fix #2647 (@pygy)](https://github.com/MithrilJS/mithril.js/pull/2655)

The bundler mangles identifier-like strings within RegExps, this works around the problem by not using such RegExps.
#### [Reject request on XHR timeout (@kevinfiol)](https://github.com/MithrilJS/mithril.js/pull/2646)

Derived from PR #2581.  Allows requests to properly reject on event of a timeout.
#### [Remove extra isLifecycleMethod call from removeAttr (@ZeikJT)](https://github.com/MithrilJS/mithril.js/pull/2594)

Removing an extra isLifecycleMethod in the removeAttr method, it isn't needed since it's already checked on the previous line.
#### [Fix #2601 (@dead-claudia)](https://github.com/MithrilJS/mithril.js/pull/2603)

Fix issue where ending a stream in the middle of a stream callback would result in erroneous parent stream state for the rest of that emit.  Fixes #2601.
#### [Add streams to releases again, include minified bundle, drop internal stuff from npm (@dead-claudia)](https://github.com/MithrilJS/mithril.js/pull/2539)

Add `stream/stream.js` to releases again.  Add `stream/stream.min.js` now that the process is remotely sane now.
#### [Make errors and their messages more accurate and helpful (@dead-claudia)](https://github.com/MithrilJS/mithril.js/pull/2536)

I updated error messages to be much more helpful.
#### [Fix assertion descriptions (@soulofmischief)](https://github.com/MithrilJS/mithril.js/pull/2405)

I moved the return statement to the end of define() so that it returns even if the comparison fails.
#### [Fix branch target (@dead-claudia)](https://github.com/MithrilJS/mithril.js/pull/2765)

https://github.com/MithrilJS/mithril.js/runs/6199543939?check_suite_focus=true.
#### [Automate mithril's release workflow (@JAForbes)](https://github.com/MithrilJS/mithril.js/pull/2760)

Automated releases, pre-releases, (code) rollbacks and recovery, npm publishing, change log management just by using normal github flow.
#### [Add Simple Application Flems Supporting v2.0.4 and up (@tbreuss)](https://github.com/MithrilJS/mithril.js/pull/2751)

Added Flems for Simple Application supporting v2.0.4 of Mithril.js.  Fixes Issue #2710.
#### [Make example work with webpack v5.69.1 (@StephanHoyer)](https://github.com/MithrilJS/mithril.js/pull/2757)

fixes #2634.
#### [2604: correct and move text about statements in view method (@kevinfiol)](https://github.com/MithrilJS/mithril.js/pull/2748)

Addresses #2604.
#### [WIP: Update modularisation details in Installation docs (@orbitbot)](https://github.com/MithrilJS/mithril.js/pull/2620)

added link to flems.io as an easier way to just try out the framework.  -.  Documentation has grown a bit stale.
#### [Added power support for the travis.yml file with ppc64le (@sreekanth370)](https://github.com/MithrilJS/mithril.js/pull/2644)

Added power support for the travis.yml file with ppc64le.  This is part of the Ubuntu distribution for ppc64le.
#### [Updated babel/webpack docs to work with latest versions (@pereriksson)](https://github.com/MithrilJS/mithril.js/pull/2649)

As a developer I tried setting up Mithril with Babel and Webpack but failed because of a variety of errors.
#### [[docs] route redirection using the history API (@pygy)](https://github.com/MithrilJS/mithril.js/pull/1767)

This is an attempt at fixing #1759, but there may be more to be added.  Feedback welcome.  ping @dontwork.
#### [Bump path-parse from 1.0.6 to 1.0.7 (@dependabot[bot])](https://github.com/MithrilJS/mithril.js/pull/2718)

Bumps [path-parse](https://github.com/jbgutierrez/path-parse) from 1.0.6 to 1.0.7.  Commits.  See full diff in compare view.
#### [Bump glob-parent from 5.1.0 to 5.1.2 (@dependabot[bot])](https://github.com/MithrilJS/mithril.js/pull/2693)

Bumps [glob-parent](https://github.com/gulpjs/glob-parent) from 5.1.0 to 5.1.2.  Release notes.  Sourced from glob-parent's releases.  v5.1.2.  Bug Fixes.
#### [Bump ajv from 6.10.2 to 6.12.6 (@dependabot[bot])](https://github.com/MithrilJS/mithril.js/pull/2741)

Bumps [ajv](https://github.com/ajv-validator/ajv) from 6.10.2 to 6.12.6.  Release notes.  Sourced from ajv's releases.  v6.12.6.  Fix performance issue of "url" format.
#### [Show previous versions (@mike-ward)](https://github.com/MithrilJS/mithril.js/pull/2353)

Add Dropdown that shows links to archived versions of the documentation.
#### [docs: improve m.request return value description (@GAumala)](https://github.com/MithrilJS/mithril.js/pull/2206)

In the m.request return value description, add a line informing that error status codes cause the promise to reject.
#### [A note on JSX events (@pereriksson)](https://github.com/MithrilJS/mithril.js/pull/2648)

Naming JSX events according to their documentation produces unexpected results with incorrectly named events when using JSX with Mithril.
#### [Document route resolution cancellation, fixes #1759 (@barneycarroll)](https://github.com/MithrilJS/mithril.js/pull/2672)

Also fixes a broken internal link.
#### [Bump marked from 0.7.0 to 4.0.10 (@dependabot[bot])](https://github.com/MithrilJS/mithril.js/pull/2717)

Bumps [marked](https://github.com/markedjs/marked) from 0.7.0 to 4.0.10.  Release notes.  Sourced from marked's releases.  v4.0.10.  4.0.10 (2022-01-13).  Bug Fixes.
#### [Flems in docs (#2348) [skip ci] (@porsager)](https://github.com/MithrilJS/mithril.js/pull/2348)

Added flems instead of the current codepen samples.
#### [Remove old TOC link (@ArthurClemens)](https://github.com/MithrilJS/mithril.js/pull/2698)

Content was moved some time ago and linked section no longer exists.
#### [Cavemansspa patch 1 (@cavemansspa)](https://github.com/MithrilJS/mithril.js/pull/2696)

Documentation update.
#### [Bump hosted-git-info from 2.8.4 to 2.8.9 (@dependabot[bot])](https://github.com/MithrilJS/mithril.js/pull/2684)

Bumps [hosted-git-info](https://github.com/npm/hosted-git-info) from 2.8.4 to 2.8.9.  Changelog.  Sourced from hosted-git-info's changelog.  2.8.9 (2021-04-07).
#### [Bump lodash from 4.17.20 to 4.17.21 (@dependabot[bot])](https://github.com/MithrilJS/mithril.js/pull/2680)

Bumps [lodash](https://github.com/lodash/lodash) from 4.17.20 to 4.17.21.  Commits.  f299b52 Bump to v4.17.21.
#### [Bump handlebars from 4.7.6 to 4.7.7 (@dependabot[bot])](https://github.com/MithrilJS/mithril.js/pull/2679)

Bumps [handlebars](https://github.com/wycats/handlebars.js) from 4.7.6 to 4.7.7.  Changelog.  Sourced from handlebars's changelog.  v4.7.7 - February 15th, 2021.
#### [Delete test-utils/README.md (@dead-claudia)](https://github.com/MithrilJS/mithril.js/pull/2674)

We don't expose this publicly anymore, so there's literally no justification for this file's existence.
#### [simple-application.md: consistent use of type=submit (@danbst)](https://github.com/MithrilJS/mithril.js/pull/2657)

When following tutorial and typing everything in, I was confused that Save button didn't work.
#### [Fix inconsistent capitalizations of "JavaScript" (@mtsknn)](https://github.com/MithrilJS/mithril.js/pull/2639)

"Javascript"/"javascript" → "JavaScript".  Fixes #2398, or at least I can't find any more incorrect capitalizations.
#### [fix some typos (@osban)](https://github.com/MithrilJS/mithril.js/pull/2487)

Found some typos.  Mainly unescaped `|` in tables, but also a few other irregularities.  Not all problems are visible in the website docs.
#### [Replace mocha by ospec in testing page (@gamtiq)](https://github.com/MithrilJS/mithril.js/pull/2585)

Fixed a typo in testing doc page.  Currently there is reference to `mocha` in the page whereas `opsec` is used.
#### [Bump acorn from 7.1.0 to 7.4.0 (@dependabot[bot])](https://github.com/MithrilJS/mithril.js/pull/2630)

Bumps [acorn](https://github.com/acornjs/acorn) from 7.1.0 to 7.4.0.  Commits.  54efb62 Mark version 7.4.0.
#### [Bump handlebars from 4.4.2 to 4.7.6 (@dependabot[bot])](https://github.com/MithrilJS/mithril.js/pull/2629)

Bumps [handlebars](https://github.com/wycats/handlebars.js) from 4.4.2 to 4.7.6.  Changelog.  Sourced from handlebars's changelog.  v4.7.6 - April 3rd, 2020.
#### [Bump lodash from 4.17.15 to 4.17.20 (@dependabot[bot])](https://github.com/MithrilJS/mithril.js/pull/2628)

Bumps [lodash](https://github.com/lodash/lodash) from 4.17.15 to 4.17.20.  Commits.  ded9bc6 Bump to v4.17.20.  63150ef Documentation fixes.
#### [Bump minimist from 1.2.0 to 1.2.3 (@dependabot[bot])](https://github.com/MithrilJS/mithril.js/pull/2627)

Bumps [minimist](https://github.com/substack/minimist) from 1.2.0 to 1.2.3.  Commits.  6457d74 1.2.3.  38a4d1c even more aggressive checks for protocol pollution.
#### [Update installation.md (@purefan)](https://github.com/MithrilJS/mithril.js/pull/2608)

Offer to install mithril as a webpack plugin.  Just makes my life easier by not having to include mithril in every one of my js files.
#### [replace slave label with replica (@stephanos)](https://github.com/MithrilJS/mithril.js/pull/2605)

One of the example is using the antiquated word "slave" for a database replica.  I updated the language and tested the change.
#### [ES6 and m.trust docs patch (@kczx3)](https://github.com/MithrilJS/mithril.js/pull/2593)

While reading through some of the documentation I saw some issues with both the ES6 and `m.trust` pages.
#### [docs: Fix simple typo, subsequece -> subsequence (@timgates42)](https://github.com/MithrilJS/mithril.js/pull/2582)

There is a small typo in mithril.js, render/render.js.  Should read `subsequence` rather than `subsequece`.
#### [change link to go to ospec instead of mocha (@akessner)](https://github.com/MithrilJS/mithril.js/pull/2576)

Change the link to point to ospec docs in github.  ospec link went to mochajs.  [issue 2575](https://github.com/MithrilJS/mithril.js/issues/2575).  N/A.  N/A.  N/A.
#### [updated to the Vimeo showcase (@CreaturesInUnitards)](https://github.com/MithrilJS/mithril.js/pull/2573)

The scrimba version of Mithril 0-60 was built on their beta platform, and doesn't really even work anymore.
#### [Exclude archive of previous docs (@cztomsik)](https://github.com/MithrilJS/mithril.js/pull/2561)

update .npmignore so that archives are not included in the resulting package.  space/bandwidth savings.  fix #2552.
#### [Pimp the docs linter (and assorted changes) (@pygy)](https://github.com/MithrilJS/mithril.js/pull/2553)

Add an optional cache for faster runs.  Add a final report.  Don't return anything from `exec()`.  Cover more files.  Look for a "--cache" option.
#### [Recast key docs to be much clearer and more accurate (@dead-claudia)](https://github.com/MithrilJS/mithril.js/pull/2540)

Recast key docs to be much clearer and more accurate, including a few Flems examples to help intuitively explain things.
#### [Add `m.censor`, adjust `m.route.Link` to use it (@dead-claudia)](https://github.com/MithrilJS/mithril.js/pull/2538)

Add `m.censor`.  Adjust `m.route.Link` to use it.  Restructure a few things for better code reuse.  Fixes #2472.
#### [Update fetch() browser support in docs (@qgustavor)](https://github.com/MithrilJS/mithril.js/pull/2522)

As [Can I use](https://caniuse.com/#feat=fetch) shows `fetch()` supported since Safari 10.1 and iOS Safari 10.3.
#### [docs: Add release dates to all change-log files (@maranomynet)](https://github.com/MithrilJS/mithril.js/pull/2513)

I'd like to introduce release dates to the change log files.  Release dates are human-friendly and add a bit of historical perspective to change-log files.
               
<a name="changelog-end"></a>

### CODE REVIEW

**Comment by StephanHoyer** [comment]
do we really have one version jump for every merged pr, @JAForbes ?

**Comment by pygy** [comment]
[It looks like it is the case](https://github.com/JAForbes/pr-release/blob/50c6691948e0053e76fd55b6e6349e8a824c3894/lib/index.js#L210-L222).

Something along this would be closer to what we want I think:

```JS

const level = ['none', 'prerelease', 'patch', 'minor', 'major' ]
  .reduce((current, candidate) => severityIdx[candidate]?.length ? candidate : current)
let nextVersion 
if (level === 'none') {
  // prerelease business
} else 
  nextVersion = semver.inc(semver.clean(version), level)
}

```

**Comment by JAForbes** [comment]
Yeah that is how it works, but I could add some alternate versioning logic.  Do you want it to do the minimum necessary semver bump?  E.g. last release was 2.0.4, there was at least 1 minor, so this release is 2.1.0?

**Comment by pygy** [comment]
> Do you want it to do the minimum necessary semver bump?

This is a concise version of what I tried to express with code, yes... Let's see what the others think

**Comment by StephanHoyer** [comment]
It worked @JAForbes 🎉

**Review by dead-claudia — APPROVED** [review]

**Pull request merged**
