### PR TITLE
Replace backticks in code example

### PR DESCRIPTION
**Pull request by ArthurClemens**
The backticks were messing up the rendered documentation at https://mithril.js.org/es6.html

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have updated `docs/change-log.md`

### CODE REVIEW

**Comment by osban** [comment]
@ArthurClemens eh, duplicate of #2501 😉

**Comment by isiahmeadows** [comment]
I prefer quotes to no quotes anyways for this, so I'll go ahead and merge.

**Comment by isiahmeadows** [comment]
@osban Sorry for completely laying your PR to the wayside here - I still want to troubleshoot those issues, and I was planning on patching yours to use quotes and then merging, just I never got around to it. (It's relatively low priority for me ATM.)

**Comment by osban** [comment]
@isiahmeadows no worries 👍

**Pull request merged**
