### PR TITLE
Fix assertion descriptions

### PR DESCRIPTION
**Pull request by soulofmischief**
## Description

I moved the return statement to the end of define() so that it returns even if the comparison fails.

## Motivation and Context

This should fix https://github.com/MithrilJS/mithril.js/issues/2391

## How Has This Been Tested?

I eyeballed it. ;) 
It's a very short function, could be a pop quiz on the blackboard and @isiahmeadows describes the problem and solution in https://github.com/MithrilJS/mithril.js/issues/2391#issuecomment-470377678

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have updated `docs/change-log.md`

### CODE REVIEW

**Comment by soulofmischief** [comment]
I figured there were already tests in place, I didn't bother looking. I'll get on that.

**Comment by soulofmischief** [comment]
@isiahmeadows I found some time to poke through opsec and understand how this needed to be done

**Comment by isiahmeadows** [comment]
Could you update your local branch and fix the merge conflict?

**Comment by soulofmischief** [comment]
Ok, should be okay now.

**Comment by soulofmischief** [comment]
My apologies, I made a quick edit using Github's interface without thinking. I'll fix it in a local repo so I won't run afoul of the editorconfig.

**Comment by soulofmischief** [comment]
Btw if you want to enforce the style rule of requiring curly braces for multi-line if statements, setting the `curly` option in `eslintrc.js` to `["error", "multi-line"]` will do the trick. This will require them for  `if`, `else`, `for`, `while`, and `do`, which is probably welcome for consistency if you want it for `if`.

**Pull request merged**
