### PR TITLE
Release - v3.0.0

### LINKED ISSUE #2682: Remove `m.jsonp`
**Mithril version:**

**Platform and OS:**

**Project:**

**Is this something you're interested in implementing yourself?** Yes

### Description

Remove `m.jsonp`

### Why

It's legacy crud to support an API style that's been almost entirely replaced with CORS, and I've not seen a JSON-P endpoint for a public API in years. It only really continued to exist as long as it did because IE 9 didn't support CORS, leaving JSONP as the only realistic way to request data there from other origins. But as even IE 10 supports it now and we're planning on sunsetting IE support entirely relatively soon, it adds nothing to keep it in Mithril.

### Possible Implementation

1. Remove `m.jsonp`
2. Inline all the abstractions into `m.request` as appropriate

### Open Questions

Do we want to continue to support this legacy API? (I strongly say we shouldn't, and I anticipate most of us would agree here.)

### LINKED ISSUE #2763: m.route.param() omits trailing slash on three-dots pattern
In my project I'm trying to fetch some dynamic path data, so I've decided to store path info as an url parameter. While doing this I've noticed, that `m.route.param(key)` returns value without trailing slash (even if it was provided in the url). 

That is the example:

```
m.route(document.body, "/list/static/index.css", {
  "/list/:path...": {
    view: function(vnode) {
      console.log("route.get():", m.route.get());
      console.log("m.route.param():", m.route.param());
    }
  },
});
```

So if you navigate to `/#!/list/static/index.css` the output would be correct:
```
route.get(): /list/static/index.css
m.route.param(): Object { path: "static/index.css" }
```
But if you navigate to some directory like `/#!/list/static/` the trailing slash in the output would be truncated: 
```
route.get(): /list/static/
m.route.param(): Object { path: "static" }
```

I expect `m.route.param("path")` should return `"static/"` -- one with trailing slash

**Mithril.js version: mithril@2.0.4**

**Browser and OS:**
Same result in latest chrome (v100) and firefox (v91.8)

## Context
I've played around and come to some workarounds:
1. Write custom router and make regex to parse path argument
2. Move some arguments to url query params, but it looks ugly

### LINKED ISSUE #2780: vnode.domSize is wrong in fragments when a child has a delayed removal
**Mithril.js version:**
v1.0 -> v2.2

## Code

```javascript
const a = m.fragment({}, [
  'a',
  m('', {
    onbeforeremove({dom, domSize}){
      return new Promise(()=>{})
    }
  }, 'b'),
  'c'
])

const b = m.fragment({onupdate({dom, domSize}){
  console.log("parent", {dom, domSize})
  console.log(document.body.childNodes.length)
}}, [
  'a',
  null,
  'c'
])

m.render(document.body, a)
m.render(document.body, b)
```

[flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvAHTSrThoAIMOBeDrfGABOGAOY5aACmABfEh2TMOHAOQYVJJf0kqNHYFuXUARjDCUhMS1koA3GNIAmlLPOdYAyhABeMGQEoDNGUQjksaAFchYLQYAHcOAAUhFwg4B0l-HgA+WX9DDhktOVVjFX9NYNVyFWYAXXy0ZlZ2DmNefkERcXoaaWoIgAdHDDonFzcXL18AoOUWylh8KEpRSUYQQYxLWg35YHdJzx8-RvnqOEWYZdXJZ3IIiRp8Y0pHAE98cgALaEcAOTe8GW9FENG+jRkJUUVTUGi0aAiUCglWUKhq9UazAEO0cVjulAeTxeb3e8gwjRx9DxQgJRN6JI+8mMjRAZHSsHINAgFzwACY+YgAAwAWgAjMKQDI6mQoBA0ABrBAodDYXCIEBYCDgoTQNkgKJQPDfGg0QZwRAAektETQgwVoi+LktWp10AAAnz8F6+S7td9dVB8Fq0ERSCAaO9BuqQHByLrBjQpXUZEA)

## Steps to Reproduce
1. render a fragment with several nodes (`[a, b, c]`), one of them (`b`) with an `onbeforeremove` hook that delays node removal.
2. render the same fragment, but with said node removed from vdom check the fragment's `vnode.domSize` in `onupdate`.

## Context
We should provide users a way to reach the nodes of the fragment. Both the nodes in vdom and the nodes present in DOM. Currently the docs recommends to rely on `domSize` for fragments, but doing so would let users grab `[a, b]`, not `[a, c]` nor `[a,b,c]` which would both be less wrong.

Both `[a, c]` and `[a,b,c]` could be retrieved by scanning vdom. Providing an iterator would seem ideal to me.

Someting like this (untested) helper would let folks iterate using `for (dom of domFor(vnode))` loops.

```js
const delayedRemoval = new WeakSet

function* domFor({dom, domSize}) {
  if (domSize == null) {
    if !delayedRemoval.has(dom) yield dom
  } else {
    let i = 0
    while (i < domSize) {
      if (!delayedRemoval.has(dom)) {
        yield dom
        i++
      }
      dom = dom.nextSibling
    }
  }
}
```
At the very least, the limitation should be documented.

### PR DESCRIPTION
**Pull request by JAForbes**
# Release v3.0.0

<a name="changeSummary-start"></a>

- #2811
- #2796
- #2793
- #2790
- #2762
- #2782
- #2786
- #2785
- #2781
- #2779
- #2746
- #2764

<a name="changeSummary-end"></a>
        
## Changelog

<a name="changelog-start"></a>
#### [Actually remove ospec from the main code base  (@pygy)](https://github.com/MithrilJS/mithril.js/pull/2786)

It is still used as a `dev-dependency`.
#### [Bump terser from 4.3.4 to 4.8.1 (@dependabot[bot])](https://github.com/MithrilJS/mithril.js/pull/2796)

Bumps [terser](https://github.com/terser/terser) from 4.3.4 to 4.8.1.  Changelog.  Sourced from terser's changelog.  v4.8.1 (backport).
#### [implement m.domFor() and use it internally to move and remove nodes. Fix #2780 (@pygy)](https://github.com/MithrilJS/mithril.js/pull/2782)

Add `m.domFor(vnode)`.  This adds `m.domFor(vnode)` as described in #2780 (with a twist to deal with node removal between iterations).
               
#### [Bypass css text (@pygy)](https://github.com/MithrilJS/mithril.js/pull/2811)

Shave a few bytes by setting `element.style` directly, rather than `element.style.cssText`, since the former is now supported everywhere relevant.
#### [Fix silent build error in next: bundler can't handle multiple exports per module (@barneycarroll)](https://github.com/MithrilJS/mithril.js/pull/2793)

The `domFor` patch breaks the compiled output: the bundler can't handle multiple exports per module.  1.
#### [Bump shell-quote from 1.7.2 to 1.7.3 (@dependabot[bot])](https://github.com/MithrilJS/mithril.js/pull/2790)

Bumps [shell-quote](https://github.com/substack/node-shell-quote) from 1.7.2 to 1.7.3.  Changelog.  Sourced from shell-quote's changelog.  1.7.3.
#### [Bump minimist from 1.2.5 to 1.2.6 (@dependabot[bot])](https://github.com/MithrilJS/mithril.js/pull/2762)

Bumps [minimist](https://github.com/substack/minimist) from 1.2.5 to 1.2.6.  Commits.  7efb22a 1.2.6.
#### [Add back CI (@pygy)](https://github.com/MithrilJS/mithril.js/pull/2785)

Enable CI that was I suppose disabled by mistake.
#### [Add missing prerelease branch target. (@JAForbes)](https://github.com/MithrilJS/mithril.js/pull/2781)

Addresses this issue https://github.com/JAForbes/pr-release/issues/345 (raised by @pygy).
#### [Kick jsonp - fixes #2682 (@StephanHoyer)](https://github.com/MithrilJS/mithril.js/pull/2779)

Kick JSONP.  I removed all stuff related to jsonp.  It's only rarely used nowadays, If anyone needs it, there are plenty of alternative packages.
               
<a name="changelog-end"></a>

### CODE REVIEW

**Comment by pygy** [comment]
@JAForbes the pr action failed here, not sure what happens or if I can re-run it safely...

**Comment by pygy** [comment]
@JAForbes I messed up with the v2.x branch and accidentally triggeredpr-release to run from there, i.e. the wrong branch.

It would be nice if there were branch checks before doing irreversible operations (and possibly other idiot proofing measures).

Also, from here, how do we fix things up?

**Comment by Prid13** [comment]
Was the wrong version released as 2.2.3? :O

**Comment by pygy** [comment]
Yes, I messed up while setting up the v2.x branch and triggered the `release` script by accident.

It was up for about one hour and a half, I hope it didn't derail your workflow...

**Comment by Prid13** [comment]
No, not at all, was just testing Mithril when I noticed some changes that I had to investigate 😅

Oh, it's fixed already? Sadly the Mithril CDN link I found on Google as the top result still holds that wrong version: https://cdnjs.com/libraries/mithril :/

**Comment by pygy** [comment]
Oh, thanks for the heads up. Not sure I can solve this on their hand, short of pushing yet another release...

**Pull request merged**
