### PR TITLE
Officially drop IE9-10 support, pull out our hacks

### PR DESCRIPTION
**Pull request by isiahmeadows**
## Description

- I also fixed a bunch of related comments
- I had to polyfill `requestAnimationFrame` for Node
- Drive-by: run `eslint . --fix`
- Drive-by: update transpiling info in CONTRIBUTING.md
- Drive-by: we aren't the only ones going semicolon-free

## Motivation and Context

Spurred by some recent Gitter discussion: https://gitter.im/mithriljs/mithril.js?at=5beb8483fee6703aaf68b18b

## How Has This Been Tested?

N/A: the only functional code change wasn't specifically tested for anyways.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation change

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have updated `docs/change-log.md`

### CODE REVIEW

**Comment by ProtonScott** [comment]
I'm using mithril in a project that is used in IE9, does this mean that it will still work if I use some core-js polyfills or something?

Right now I'm using bluebird to polyfill Promises.

I can't kill it, unfortunately.

**Comment by isiahmeadows** [comment]
@ProtonScott Are you running this on Windows Server or Windows Embedded? If so, I'll consider looking into supporting IE9 (as it's still [supported by Microsoft](https://support.microsoft.com/en-us/help/17454/lifecycle-faq-internet-explorer)), but since Microsoft does not support IE9/10 for desktop, support for there is pretty much out of the equation.

Also, keep in mind v1 still supports it. v2 is what would break that support.

**Comment by isiahmeadows** [comment]
And @ProtonScott You *could* continue to use it with polyfills, just you may run into bugs with IE9's lack of support for strict mode.

**Comment by isiahmeadows** [comment]
@ProtonScott If you in fact are running this on Windows Server 2008 (IE 9), please file a new issue, and we'll take a look at it.

**Comment by ProtonScott** [comment]
> @ProtonScott Are you running this on Windows Server or Windows Embedded? If so, I'll consider looking into supporting IE9 (as it's still [supported by Microsoft](https://support.microsoft.com/en-us/help/17454/lifecycle-faq-internet-explorer)), but since Microsoft does not support IE9/10 for desktop, support for there is pretty much out of the equation.
> 
> Also, keep in mind v1 still supports it. v2 is what would break that support.

@isiahmeadows  I know you closed this no bigs, but I just wanted to clarify:

I am not using it on Windows Server or Embedded. Its a legacy app that has to work with some state goverment agencies: there are a few (sub 2% of clients, but the state mandates that we have 100% support for all) that are on IE8 or 9. 95% of it is IE11 and a few percentage poitns is IE10, but we still ahve to support those until I believe late next year or Jan 1 2020, not that it matters.

I'm not worried. I'll just polyfill the best I can. If there is a persistent issue i'll just file tickets and such, its all suppose to get upgraded soon enough I believe. Just wanted to get some idea of scope :)

**Pull request merged**
